- .travis.yml
- scripts/ci/build.sh
- scripts/ci/cleanup.sh
- scripts/ci/env.sh
- scripts/ci/install.sh
- scripts/ci/test.sh
Add travis support to the extension repository
> chore(ls): add travis configuration

- client/src/extension.ts
- server/src/documents.ts
> fix(ls): improve windows file escaping

- client/package.json
- server/package.json
- server/src/documents.ts
- server/src/editorServices.ts
- server/yarn.lock
refactor: update for `typescript@2.1.5`
fix: don't crash on unknown url styles
Fixes #41
> build: update to `@angular/langauge-service@2.4.6` and `typescript@2.1`

- .gitignore
- README.md
- server/package.json
- server/src/server.ts
Updated .gitignore and README.md
> build: update to `@angular/language-service@4.0.1`

- server/src/server.ts
> fix: remove unsupported snippet syntax

- client/package.json
- server/package.json
Moves to TypeScript 2.3.4 and Language Service 4.3.0-beta.0 and updates VS code dependencies.
> release: cut the `0.1.4` release

- client/package.json
> Update package to mark the extension as multi-root ready

- server/src/editorServices.ts
This commit fixes a typo `languageServiceDiabled` -> `languageServiceDisabled`
> Fix typo in editorServices.ts

- client/yarn.lock
- server/yarn.lock
This commit updates the lock files for both client and server.
> build: Update lockfiles

- client/README.md
- client/package.json
- server/package.json
- server/src/editorServices.ts
- server/yarn.lock
- tests/tools/package.json
- tests/tools/yarn.lock
> Upgrade to Angular 8.1.0

- server/src/editorServices.ts
This allows the use of non-spec tsconfig.json
Closes https://github.com/angular/angular/issues/21729
Closes https://github.com/angular/vscode-ng-language-service/pull/323
Closes https://github.com/angular/vscode-ng-language-service/issues/314
> use ts.parseConfigFileTextToJson() instead of JSON.parse()

- server/src/server.ts
https://github.com/angular/angular/pull/31972 changes the Angular LS
interface to return TS data types. This PR makes the extension
compatible with both the old and new interface.
> feat: Backwards compat with new TS LS interface

- .gitignore
- server/src/editorServices.ts
Fixes #350, angular/angular#32062 and probably fixes #339 and #336
> fix: retain the configured project even when closing last opened file from the project. 

- client/src/extension.ts
- client/src/protocol.ts
- server/src/project_service.ts
- server/src/protocol.ts
This is a feature requested in #336
> feature: Display loading indicator while project is loading

- server/src/server.ts
Fly-by removal of superfluous conditional check.
> refactor: cleanup of unnecessary branch check

- server/src/tests/utils_spec.ts
- server/src/utils.ts
> WIP: fix: use URI.file for converting file path to uri.

- .travis.yml
- scripts/e2e.sh
- scripts/format.sh
PR closes https://github.com/angular/vscode-ng-language-service/pull/405
> ci: Check diff in format.sh only in CI mode

- server/src/session.ts
This PR disables the language service for a particular project if it is
not an Angular project. The detection mechanism relies on the presence
of `@angular/core/core.d.ts` file in the program.
PR closes https://github.com/angular/vscode-ng-language-service/issues/391
> feat: Disable language service for non-Angular projects

- integration/lsp/smoke_spec.ts
- integration/project/package.json
- integration/project/yarn.lock
- server/package.json
- server/yarn.lock
Also remove @angular/language-service in test project.
This allows us to maintain only a single version in the entire
repository.
> feat: Use @angular/language-service 9.0.0-next.10

- server/package.json
- server/yarn.lock
This version contains the fix or new features #381, #255, angular/angular#33127, angular/angular#32565
> feat: Use @angular/language-service 9.0.0-next.11

- CHANGELOG.md
- README.md
- scripts/build.sh
This will show up in vscode to inform users of changes and new features.
> docs: Add CHANGELOG.md

- server/src/session.ts
This commit creates a timer to keep track of the last change made by the
user, and sends the diagnostics only after user stops typing.
Currently, it triggers for every change, and slows down the entire
operation.
A default delay of 200ms is consistent with TypeScript.
PR closes https://github.com/angular/vscode-ng-language-service/issues/432
> fix: Produce diagnostics only after user stops typing

- server/src/server.ts
PR closes https://github.com/angular/vscode-ng-language-service/issues/268
> feat: Print process ID of server process for easier identification

- client/src/extension.ts
VS Code Insider launches extension in debug mode by default, but users
install prod bundle so we have to check whether dev bundle exists, and
fall back to prod bundle if it does not.
PR closes https://github.com/angular/vscode-ng-language-service/issues/449
> fix: check dev bundle exists when in debug mode

- scripts/build.sh
Test files should not end up in prod build.
> build: do not copy test files to syntaxes directory

- syntaxes/README.md
Adds information about adding a new grammar for Angular source code,
information about data needed for testing, and how to update snapshot
tests.
> docs: add documentation for syntaxes directory

- package.json
- scripts/format.sh
- yarn.lock
Adds a script for formatting and testing the formatting of grammar JSON files with prettier.
> test: add formatting script and test for grammars

- server/src/version_provider.ts
Minimum TypeScript version should be 3.7
> fix: require min typescript v3.7

- syntaxes/template.json
- syntaxes/test/data/template.html
- syntaxes/test/data/template.html.snap
This commit adds a TextMate grammar for highlighting template binding
(microsyntax) expressions.
Part of #483.
> feat: add grammar for template bindings

- syntaxes/inline-template.json
- syntaxes/src/inline-template.ts
- syntaxes/test/cases.json
- syntaxes/test/data/inline-template.ts
- syntaxes/test/data/inline-template.ts.snap
> Do not match inline template grammars inside a template itself

- server/src/session.ts
The method above could be merged with `Session.getLSAndScriptInfo()`,
so we don't need to have so many layers of indirection.
> refactor: remove Session.getDefaultLanguageService()

- integration/lsp/ivy_spec.ts
- server/src/session.ts
After opening a file, TypeScript does a cleanup step to remove/close
"orphaned" projects: https://github.com/microsoft/TypeScript/blob/a894f8ad2b0ff35b1bcfd91defba994136c68b18/src/server/editorServices.ts#L3337
As part of this, TS checks to make sure there are no open files for the
configured project: https://github.com/microsoft/TypeScript/blob/a894f8ad2b0ff35b1bcfd91defba994136c68b18/src/server/project.ts#L2333
If the only open file for the project is an HTML file, TS will not know
about it because we do not register those with the project (instead, we
associate the template file's `ScriptInfo` with the project, but do not
make the association in the other direction).
Because we do not have this two way association between the project and
the HTML `ScriptInfo`s, TypeScript closes the …
> fix: prevent project from closing when only a template file is open

- integration/lsp/ivy_spec.ts
- server/src/session.ts
When `strictTemplates` is disabled, we know that the compiler's view of a template
is not completely "accurate". That is, the compiler's generated Type
Check Blocks will not have sufficient type information to properly
perform a rename operation.
> fix: disable rename feature when strictTemplates is disabled

- package.json
- server/package.json
- yarn.lock
Also bumped version to `v12.0.0-next.0`
> build: upgrade @angular/language-service to v12

- server/src/session.ts
Refactors the detection logic for Angular project to take into account
`@angular/core` in google3.
If internal `@angular/core` is detected, do not run ngcc.
> fix: detect @angular/core in google3 and don't run ngcc

- integration/lsp/ivy_spec.ts
- server/src/session.ts
When multiple requests of the same type are sent in quick succession, the
LSP client will automatically issue `$/cancelRequest` notification to cancel
the earlier requests.
For example, when the mouse is moving around, multiple `hover` requests could
be fired, but only the last one is meaningful to users. In this case, we
should handle the cancelled requests and not do any work.
This will significantly speed up our server's ability to process incoming
requests / notifications.
> perf: Support request cancellation

- client/src/client.ts
- package.json
https://github.com/angular/vscode-ng-language-service/issues/1191
> feat: Allow users to hide strictTemplates prompt

- .gitignore
- .ng-dev/config.ts
- .ng-dev/github.ts
- .ng-dev/merge.ts
- package.json
- yarn.lock
Set up the ng-dev toolset for the repo to allow it to be used for merging PRs.
> build: set up ng-dev toolset for the repo

- .vscode/launch.json
- .vscode/tasks.json
Add a command to launch a dev instance that uses the production .vsix.
> build: add configuration to launch prod client

- server/src/version_provider.ts
> fix: set minimum TS version to 4.2

- client/src/client.ts
`ngcc` does not work correctly for Angular projects < version 9, so
automatically switch to View Engine LS when such projects are detected in
the workspace.
Fix https://github.com/angular/vscode-ng-language-service/issues/1251
> fix: Use View Engine LS for projects < v9

- server/src/session.ts
When we do not provide a command in the code lens resolve request,
VSCode will show `!!MISSING: command!!`. Instead, we throw an error and
VSCode will simply show "no commands". It is documented that the
resolution of a code lens can throw an error here:
https://microsoft.github.io/language-server-protocol/specification#codeLens_resolve
In addition, this change ensures that the html file is part of an
angular project before returning a code lens in the first place.
Fixes #1368
> fix: avoid showing MISSING: command for code lens in templates

- server/package.json
> build(server): Update node version to match angular/angular

- .ng-dev/merge.ts
- package.json
- yarn.lock
Update the ng-dev configuration to match updated config definitions with new verison.
> build: update configuration for ng-dev

- package.json
- yarn.lock
This reverts commit 6e3d6423dde7398a063294daf90dda171170228b which
causes tests to fail
> Revert "chore(deps): update dependency jasmine to v4 (#1592)"

- integration/lsp/ivy_spec.ts
- integration/project/package.json
- integration/project/yarn.lock
This commit updates the integration project used in tests to target the v14 rc
> test: Update integration project to target v14

- CHANGELOG.md
- package.json
- server/package.json
This releases 14.2.0, and prepares us to fix #1746 by releasing the extension.
> release: v14.2.0

- WORKSPACE
[rules_ts 1.0.0](https://github.com/aspect-build/rules_ts/releases/tag/v1.0.0) was released yesterday
> chore: update to aspect_rules_ts 1.0.0

- CHANGELOG.md
Cherry pick release notes from v15 patches to main
> docs: Cherry pick release notes from v15 patches

- .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- .circleci/config.yml
- CHANGELOG.md
- package.json
- pnpm-lock.yaml
- server/package.json
- yarn.lock
This commit updates the changelog for a v17 pre release
> build: create v17.0.0-next.0 release

- server/src/session.ts
Do not disable language service for project if it has project references. Even though we couldn't find angular/core for this parent tsconfig, it might exist in the referenced projects. Disabling the language service for this root project will clean up the program for the project.
https://github.com/microsoft/TypeScript/commit/3c4c060dff2b0292d3a4d88ba0627b7657d67e7f#diff-fad6af6557c1406192e30af30e0113a5eb327d60f9e2588bdce6667d619ebd04R973-R983 We need to keep this language service and program enabled because referenced projects don't load until we open a client file for that project.
fixes #1959
> fix(server): Do not disable language service for solution style root tsconfig

- .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- integration/lsp/BUILD.bazel
- integration/lsp/ivy_spec.ts
- integration/project/app/app.component.ts
- integration/project/app/foo.component.ts
- package.json
- pnpm-lock.yaml
- yarn.lock
Updates to the latest version of the Angular language-service package.
> build: update to latest version of language-service

- .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- CHANGELOG.md
- package.json
- pnpm-lock.yaml
- yarn.lock
This commit updates to the final RC, including a few more fixes.
> build: cut 19.0.2 release of vscode extension

- .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- package.json
- pnpm-lock.yaml
- server/package.json
- yarn.lock
Updates to the latest version of Angular which includes some language service fixes.
> build: update to the latest Angular version

- CHANGELOG.md
- package.json
> build: cut v19.0.3 release

- .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- pnpm-lock.yaml
`bazel run @npm//:sync` triggers these changes
> build: update lock file

- .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- CHANGELOG.md
- package.json
- pnpm-lock.yaml
- yarn.lock
> build: publish v19.0.4 of language service extension

- .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- CHANGELOG.md
- client/src/tests/embedded_support_spec.ts
- package.json
- pnpm-lock.yaml
- server/package.json
- yarn.lock
> build: cut v19.2.2 version of language service

- .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- .circleci/config.yml
- WORKSPACE
- client/src/tests/embedded_support_spec.ts
- package.json
- pnpm-lock.yaml
- server/src/session.ts
- yarn.lock
Updates the repo to Angular v20 and Node 22.
> build: update to Angular v20

- renovate.json
This change uses the dev-infra preset.
> ci: refactor renovate config to use dev-infra preset
