server/src/server.ts
The file watchers of TypeScript defaults to using polling (avoiding a watch bug in certain versions of node) which causes the language service to consume about %10 of the CPU checking for file and directory changes. The Code Helper does not have the watch bugs so shouldn't use polling.
This forces TypeScript to use `fs.watchFile` and `fs.watchDirectory` instead.
=> fix: force TypeScript to use the non-polling file and directory watchers

.gitignore
`yarn.lock` files are left in the tree during testing. They should be ignored.
=> build: remove test yarn.lock from git tracking

client/package.json, server/package.json, server/src/editorServices.ts
Fixes the package name to remove duplicate market place entry.
Harden against common a null encountered in the wild.
Update to 0.1.7
Fixes: #157, #156
=> release: cut the `0.1.7` release

client/src/extension.ts
Adds the `RevealOutputChannelOn.Never` option to the language client to stop the window from popping open.
Closes #187
=> Add revealOutputChannelOn to language client

.travis.yml, tests/tools/mock-host/index.ts
This commit fixes the flaky CI test due to the termination of JSON-RPC
client (mock-host) before the server actually processes all requests.
=> fix: Flaky test on CI due to mock-host timeout

client/package.json
This commit removes "beta" from the version as it does not conform to
the version string format specified by VSCode marketplace.
=> release: version 0.1.10-beta to 0.1.10

client/package.json, scripts/ci/build.sh
The build script assumes that vsce is available in the global directory.
This commit adds vsce to the dev dependencies and invoke the local copy
instead.
=> build: Add vsce to dev dependencies

client/src/extension.ts, server/src/server.ts
Setting the environment variable in the code after the process is
launched is too late. It has no effect. Instead, the parameter should be
specified as part of the server process spawn options.
=> fix: TSC_NONPOLLING_WATCHER should be set when process is spawned

server/src/documents.ts, server/src/editorServices.ts
Currently the extension destroys project service while saving last opened file. This PR fixes this bug.
=> fix: avoid close project while saving file

server/src/editorServices.ts, server/src/errors.ts, server/src/server.ts
https://github.com/angular/angular/pull/32115 updates the interface
for ng.getDiagnostics() to return ts.Diagnostics[] whereas
https://github.com/angular/angular/pull/32115 updates the interface
for ng.getCompletions() to return ts.CompletionInfo.
This PR makes the extension backwards compatible with the older
interface.
=> feat: Backwards compat with new TS LS interface

server/src/editorServices.ts
This PR makes the extension to share [DocumentRegistry](https://github.com/microsoft/TypeScript/blob/e46c846ee6e20687ea4a39055f1081ba73ca89ec/src/services/documentRegistry.ts#L3-L17) instance between all instances of LanguageService.
=> share DocumentRegistry instance between all language service instances

client/src/extension.ts
This commit updates the client options and server options in the
extension in preparation for the migration to the new server.
New server supports two command line arguments:
1. `--logFile <path>`
2. `--logVerbosity <verbose, normal, terse>`
These flags are same as the ones in tsserver.js
=> update extension to support server cmd flags

.clang-format, package.json, scripts/format.sh, yarn.lock
Adds clang-format via the clang-format NPM package with Google JS/TS
formatting configuration set to 100 columns. Includes a script for
in-place formatting of TS files in the `client/`, `integration/`, and
`server/` directories. Includes a `yarn format` command that aliases
this script.
Part of #373.
=> style: add clang-format for TypeScript formatting

.gitignore, .vscode/recommended-settings.json, .vscode/settings.json, DEVELOPER.md
Document how to use the `clang-format` formatter added to this
repository in #372. Include instructions for formatting files on save
in VS Code, IntelliJ IDEs, and Vim.
Add a VS Code workspace setting configuration for enabling automatic
source code formatting with the `clang-format` VS Code extension.
Add `.vimrc` and `.nvimrc` so Vim and Neovim configurations of the
formatter are local-only.
Part of #373.
=> docs: add documentation about new `clang-format` formatter

.travis.yml, client/src/extension.ts, client/src/protocol.ts, integration/e2e/definition.test.ts, integration/e2e/helper.ts, integration/e2e/index.ts, integration/lsp/smoke_spec.ts, server/src/completion.ts, server/src/diagnostic.ts, server/src/logger.ts, server/src/project_service.ts, server/src/protocol.ts, server/src/server.ts, server/src/server_host.ts, server/src/utils.ts
Adds automated Travis CI test to ensure TypeScript files are formatted
with `clang-format`. If any files are unformatted, and error message
stating "Files not formatted; please run 'yarn format'" is given.
Also formats existing files to pass this new test.
PR Closes #373
=> test: add test for clang-format formatted files

server/src/server.ts
Before this, lsp.Location[] is returned by onDefinition, and the results
do not contain the originSelectionRange.
If user hovers over templateUrl for example, they'd see
```
@Component({
templateUrl: './app.component.html',
})
class AppComponent {}
```
`app`, `component`, and `html` highlighted separately.
Returning lsp.LocationLink[] solves this issue.
=> fix: use LocationLink for onDefinition

server/src/project_service.ts
`ProjectService.serverHost` and `ProjectService.logger` are never
actually used by `ProjectService` except in the constructor. Remove them
as properties.
=> refactor(server): remove unused ProjectService class properties

server/src/server.ts
Certain definition files (like CSS files) don't have a `scriptInfo` but
also don't need to be read, because their definition spans are of 0
length. Don't skip over such definitions.
=> fix(server): don't skip definitions with a zero-length range

server/src/project_service.ts
When `ScriptInfo` is created for non-JS/TS files other than through
`openClientFile()`, explicitly set HTML files as `ts.ScriptKind.External`.
This is used, for example, for files returned by `getExternalFiles()`.
=> fix: Always open HTML files as External Script

server/src/server.ts
`scriptInfo.getDefaultProject()` will throw if it does not have any containing project, thus it should not be used.
This could occur if only HTML file is opened in the editor, and `openClientFile()` does not return the
config file name.
=> fix: always use projSvc.getDefaultProjectForScriptInfo

server/src/project_service.ts, server/src/server.ts
This is the first part to partially address https://github.com/angular/vscode-ng-language-service/issues/391
When non-Angular TypeScript projects are opened, the Angular language service should be disabled.
Once it's disabled, the server should not call `getLanguageService()`.
=> fix: do not retrieve language service if it's disabled

client/src/commands.ts, client/src/extension.ts, package.json
This PR adds `Angular: Restart Angular server' command to the extension.
This will kill the existing language server then spawns a new process.
PR closes https://github.com/angular/vscode-ng-language-service/issues/267
=> feat: Add restart command

client/src/extension.ts, server/package.json, server/src/project_service.ts, server/src/server.ts, server/src/tests/version_provider_spec.ts, server/src/version_provider.ts, server/yarn.lock
The initial idea of the new extension is to always load
`@angular/language-service` from an Angular project that has the package
installed. That is why it does not bundle the package with the server.
However, `@angular/language-service` is not always available, due to a
few reasons:
1. The initial directory opened is not the root of an Angular project.
2. When spawned as pure LSP server, the process CWD is not where
@angular/langauge-service is installed.
Besides that, users have no control over which @angular/language-service
version they want the extension to use. (TypeScript extension provides
this feature).
It is also surprising to users that the extension does nothing if
@angular/language-service is not found.
For the reasons above, it is better that the server bundles a fallback …
=> feat: Bundle @angular/language-service with server

client/src/extension.ts, integration/lsp/smoke_spec.ts, package.json, rollup.config.js, server/package.json, server/src/banner.js, server/src/logger.ts, server/src/project_service.ts, server/src/server.ts, server/src/session.ts, server/src/tests/version_provider_spec.ts, server/src/version_provider.ts, server/yarn.lock, yarn.lock
This PR moves most of the code in server.js to a standalone module named
Session, which provides an encapsulation of LSP connection. Since
server.js is a script and not a module, it should not contain too much
code.
Improved command line parsing and added help menu.
=> feat: add Session class and refactor server.js

server/src/session.ts
`configFileErrors` returned by `openClientFile()` is an empty array even
if there's no error, so check for its length besides truthiness.
=> fix: check config file errors length

client/src/extension.ts, package.json
Rollup bundle does not work in development for a few reasons:
1. Watch mode in vscode has to wait for tsc then rollup to finish.
This might be possible by setting up one task to "dependsOn" another
task, but don't bother with this for now.
See https://code.visualstudio.com/docs/editor/tasks#_compound-tasks
2. Sourcemaps have to be enabled in rollup, otherwise breakpoints in TS
code would not work.
Besides, running rollup is relatively slow, and thus hinders development
velocity.
Removing rollup from the development workflow has no impact on
correctness, so it's safe to omit this step.
Revisit this some other time if necessary.
=> fix: use non-rollup bundle in development

server/package.json
Make @angular/language-server the official public npm package for LSP.
PR closes https://github.com/angular/vscode-ng-language-service/issues/377
=> feat: Make @angular/language-server public

client/src/extension.ts, package.json
This PR allows users to change the version of typescript and
@angular/language-service used by the server from vscode.
Instead of using process.cwd() (which is a very bad idea), the extension
client should instead look for typescript and @angular/language-service
in the workspace folders.
If there's no workspace folder, fallback to the bundled version.
=> feat: Allow users to set @angular/language-service from vscode

README.md, package.json, server/src/tests/version_provider_spec.ts, yarn.lock
Now that https://github.com/angular/angular/pull/32946 has landed,
upgrade to ts 3.6.4.
=> build: upgrade to TypeScript 3.6.4

server/src/session.ts
When making the check to determine if a project is Angular, it could be
the case that the language service is already disabled. This happens
when there are files in the project that exceeded limit.
This PR fixes the issue by first checking if the language service is
already disabled. Also added much more information to the logs to help
users diagnose the problem. Messages are logged to both remote console
(vscode) and file so that the former could inform users in their editor,
and the latter makes it much easier to correlate the sequence of events
in both TypeScript and Angular.
Related: https://github.com/angular/vscode-ng-language-service/issues/416
=> fix: Check language service is not already disabled

client/src/extension.ts, package.json
This commit adds a vscode config `angular.log` that mirrors
`typescript.tsserver.log` for setting log verbosity. This allows users
to turn on verbose logging for debugging / diagnostic purpose.
It would also help us gather much more info when users report errors.
The default value is set to `terse`, which is minimal logging.
=> feat: Allow users to set log verbosity in editor

server/src/completion.ts, server/src/session.ts
The language service returns an optional replacement span, but the
information is not propagated to the editor.
=> fix: use replacementSpan for completion if provided

integration/lsp/smoke_spec.ts
In dev mode, rollup is not used to bundle the code so that test execution is fast.
However, this means the actual bundle that is published to the marketplace is not
tested in any way. This commit changes the end-to-end test to exercise the
production bundle instead.
=> test: use rollup bundle for e2e test

server/src/cmdline_utils.ts, server/src/server.ts, server/src/tests/cmdline_utils_spec.ts
This commit moves the command line parsing methods to a standalone file
so that they can be shared with the loader (banner) later on.
This is in preparation for removing banner.js and rewrite it in TypeScript
instead to remove code duplication.
=> refactor: move command line utils to standalone module

client/src/extension.ts
This commit works around the bug in https://github.com/microsoft/TypeScript/issues/34616
and partially fixes https://github.com/angular/vscode-ng-language-service/issues/437.
=> fix: always load @angular/language-service from bundled location

server/src/banner.ts, server/src/server.ts, server/src/tests/version_provider_spec.ts, server/src/version_provider.ts
This commit refactors version_provider.ts to resolve a node module with
any minimum version, not just major version.
The same logic is now used in server.ts and banner.ts to resolve
tsserver. This enables us to accurately report the version of the
module require-d.
=> fix: use same logic to resolve typescript in banner and server

README.md
Just opening the .vsix file directly does not work. This commit
adds instructions on how to install a prerelease ,so that other users
don't run into the same issue as I did.
Fixes #450.
=> docs: add prereleae installation instructions

.github/ISSUE_TEMPLATE/bug_report.md
Markdown file requires either two trailing spaces or a newline in order
for the sentence to appear in a newline. vscode automatically removed
trailing whitespace in the previous commit, which leads to bad formatting.
=> fix: newline missing in issue template

scripts/build.sh
Currently, consecutive builds of the extension will fail because
[TypeScript always saves](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#composite-projects)
incremental compilation information in a composite project like this
one. In particular, this means that even when the output directory of
the TS compilation is removed, TypeScript doesn't realize that the
output files are no longer there because it has cached the build graph,
and thus not all the expected files are present for copying to the
extension output directory.
This commit fixes the above issue by removing TypeScript's incremental
compilation build files before rebuilding the project.
=> fix: remove incremental compilation caches across builds

package.json, scripts/build.sh, syntaxes/template.ng.json
Injects an HTML TextMate grammar in Angular component `template`
decorator properties, in TypeScript files.
The grammar is enabled in decorators with a `template` property whose
key value is a string surrounded by any number of parantheses or
whitespace.
This project owes a great deal to
https://github.com/natewallace/angular2-inline, who first enabled
Angular inline syntax highlighting.
=> feat: add syntax highlighting for embedded HTML in TypeScript

.travis.yml, package.json, scripts/format.sh, scripts/syntax.sh, syntaxes/test/html.tmLanguage-dummy.json, syntaxes/test/inline_template.ts, yarn.lock
Adds tests for the TypeScript inline Angular template grammar via the
[vscode-tmgrammar-test](https://github.com/PanAeon/vscode-tmgrammar-test) framework, which [now supports loading multiple grammars](https://github.com/PanAeon/vscode-tmgrammar-test/commit/e2c4e86cd0f365a106125f3df03208d90b11a72e)
as needed by this project.
A dummy HTML grammar is used for inline templates, as currently we are
only concerned with recognization of the inline template.
=> test: add tests for inline template textmate grammar

scripts/syntax.sh, syntaxes/template.ng.json, syntaxes/test/inline_template.ts, syntaxes/test/inline_template.ts.snap
Prevents syntax highlighting inline templates by excluding the grammar
injection on decorators with comments.
The grammar test framework does not currently support specifying grammar
rule exclusions (https://github.com/PanAeon/vscode-tmgrammar-test/issues/6),
so instead the test cases are moved to snapshot tests
that demonstrate that no other grammars are added on excluded cases.
=> fix(syntaxes): do not syntax highlight commented template properties

server/src/session.ts
When a file is first opened in the editor, we should not pass
`fileContent` to the project service, because doing so assumes that the
content in the editor is more up-to-date than the content on disk, which
is not true. We only keep track of changes of files that are already on
disk, so the content on disk is already the latest snapshot.
This is a prerequisite to remove `getExternalFiles()`.
See discussion at https://github.com/angular/vscode-ng-language-service/issues/473
=> fix: do not include fileContent when opening file

package.json, scripts/build.sh, scripts/syntax.sh, syntaxes/inline-template.json, syntaxes/test/inline_template.ts.snap
This commit performs a minor refactor, changing the TextMate inline
template syntax file name and scopes to explicitly be `inline_template`.
This is in preparation for adding a TextMate grammar for CSS styles in
`@Component` `styles` properties.
=> refactor: rename template syntax to inline_template

client/src/extension.ts, client/src/protocol.ts, integration/lsp/smoke_spec.ts, server/src/protocol.ts, server/src/session.ts
Currently, the loading indicator remains in pending state when the language service fails to load the project. Typescript project server doesn't send any event when the error occurs.
This commit refactors the loading indicator to reset state when any error occurs while opening the document.
PR closes #464
=> fix: reset loading status when the language service fails to load the project.

package.json, syntaxes/inline-styles.json, syntaxes/test/cases.json, syntaxes/test/data/inline-styles.ts, syntaxes/test/data/inline-styles.ts.snap, syntaxes/test/driver.ts, syntaxes/test/dummy/css.tmLanguage-dummy.json
Adds a TextMate grammar for inline styles in a component.
Unfortunately, we cannot merge this grammar conviniently with the one
specified for inline templates, because though the directions of grammar
recurse are similar for both, they apply different grammars for
matches. For instance, an inline template and style both match a string
literal, but the former applies an HTML grammar while the later applies
a CSS grammar. To distinguish between the two, we have to create two
different grammar recurse paths at the closest divergence of the
grammars (for convinience, at `template` and `style` properties in a
`@Component` definition).
Attached to the PR for this commit are images demonstrating this change.
The second image shows that commenting out the style property applies
the regular …
=> feat: add textmate grammar for inline CSS styles

package.json, syntaxes/inline-template.json, syntaxes/test/data/inline-template.ts.snap
Previously, HTML was not recognized as an embedded language in an
inline template because the scope matching it (source.html) was never
used in the inline template grammar. This commits fixes that and renames
the embedded scope to the colloquial "text.html", as well as adding
embedded language scopes for CSS and JavaScript.
Attached to the PR for this commit is an animated GIF with a preview of
the changes.
=> fix: correctly specify embedded languages in an Angular template

package.json, syntaxes/inline-template.json, syntaxes/template.json, syntaxes/test/cases.json, syntaxes/test/data/inline-template.ts, syntaxes/test/data/inline-template.ts.snap, syntaxes/test/data/template.html, syntaxes/test/data/template.html.snap, syntaxes/test/dummy/css.tmLanguage-dummy.json, syntaxes/test/dummy/js.tmLanguage-dummy.json
Adds a grammar for Angular interpolations. Because the grammar relies
only on regex expressions, we cannot currently support any interpolation
delimiters other than the default `{{`/`}}` -- to do more would require
a more sophisticated highlighting solution.
For convinience, everything inside an interpolation is treated as
JavaScript syntax, even though the expressions available in an Angular
interpolations are a distinct subset of JavaScript.
Attached to this PR are several before/after images of this change.
Partially addresses #483.
| | Before   | After |
|:---:| :---:       |    :----:   | 
|Inline template| <img alt="Screen Shot 2019-12-18 at 11 23 55 AM" src="https://user-images.githubusercontent.com/20735482/71110496-04a13300-218d-11ea-8ca3-4db23a4474a7.png">| <img alt="Screen Shot …
=> feat: add syntax highlighting grammar for interpolations

syntaxes/test/cases.json, syntaxes/test/driver.ts
Names each syntaxes test case and runs each case in an individual spec
rather than having all cases run as one spec. Provides more meaningful
output on failures.
=> test: split syntaxes tests into individual specs with names

syntaxes/inline-template.json, syntaxes/test/dummy/html.tmLanguage-dummy.json
The `html.basic` grammar whitelists only W3 and custom HTML elements.
Some Angular users may use elements that do not have the custom format
(hyphen-separated), so just whitelist all elements. Fixes cases like
`<popover></popover>` being highlighted incorrectly.
Closes #526.
=> fix: whitelist all html elements

syntaxes/template.json, syntaxes/test/data/template.html, syntaxes/test/data/template.html.snap
Adds syntax highlighting support for template property bindings. In
particular, the expression in the bound property value is highlighted as
JavaScript syntax.
The screenshot attached to the PR for this commit demonstrates the
change.
Partially addresses #483
Closes #253
=> feat: add textmate grammar for template property bindings

syntaxes/template.json, syntaxes/test/data/template.html, syntaxes/test/data/template.html.snap
- Strictly defined characters in the attribute name pattern (fixes #539)
- Reversed the order of `string.quoted.html` and `punctuation.definition.string.begin/end.html` scopes (TM grammar scopes go from less specific on the left to more specific on the right)
- **Angular bindings** given a unique scope (`ng-binding.html`) — this scope covers the entire key/value pair, analogous to the HTML grammar's `meta.attribute.<attribute-name>.html` scope
- **Angular binding attribute names** given a unique scope in addition to `entity.other.attribute-name.html` (`entity.other.ng-binding-name.html`) — this scope covers the entire _key_, including punctuation
- **Punctuation** in Angular binding keys given unique scopes:
- **Brackets and parens** get …
=> feat: more detailed grammar scopes for template property binding syntax

syntaxes/template.json, syntaxes/test/data/template.html, syntaxes/test/data/template.html.snap
This PR adds TextMate grammar scopes for event binding syntax in Angular templates — identical to the property binding syntax but with scope names changed where appropriate. (Partially addresses #483)
Changes from the default HTML grammar:
- The entire attribute key-value pair gets the scope `meta.ng-binding.event.html`
- The attribute key (inlcluding punctuation) gets `entity.other.ng-binding-name.event.html` (in addition to `entity.other.attribute-name.html` as a fallback)
- Parens in the attribute key get `punctuation.definition.ng-binding.begin/end.html`
- Dots in the attribute key get `punctuation.accessor.html`
- The attribute value is parsed as embedded JavaScript
Screenshot with the default VS Code Dark theme:
And with a custom theme designed to support the scopes:
=> feat: textmate grammar for template event bindings

package.json, yarn.lock
https://github.com/angular/angular/pull/33717 upgraded Angular monorepo
to TypeScript 3.7.4, so we could now upgrade to ts 3.7
This would fix the error with "no config file found for *.html" if no
TypeScript file is open.
PR closes https://github.com/angular/vscode-ng-language-service/issues/546
=> build: upgrade typescript to 3.7.4

client/src/extension.ts
Now that the extension is on TS 3.7.4, we can re-enable this feature.
=> feat: renable probing language service and tsserver from active worspace

client/src/extension.ts
This commit refactors the client code to priortize the bundled version
over workspace version when resolving both typescript and
`@angular/language-service`.
This is important for good user experience so that users automatically
get the latest version that's thoroughly tested when they upgrade the
extension.
For a complete reasoning of the work and follow up discussion see
https://github.com/angular/vscode-ng-language-service/issues/556
=> feat: Prioritize workspace version when resolving ts and ng

syntaxes/template.json, syntaxes/test/data/template.html, syntaxes/test/data/template.html.snap
This commit adds a TextMate grammar for highlighting two-way bindings.
Part of #483.
=> feat: add grammar for two-way bindings

integration/lsp/smoke_spec.ts, server/src/session.ts
Trigger autocomplete on '$' for variables like '$event' and '$implicit'
in template bindings.
=> feat: Trigger autocomplete on '$' character

README.md
Having the version hardcoded in the docs make it prone to go out of
date, and now that we prioritize the bundled version, users should
automatically get the latest typescript.
=> docs: remove typescript version from README

client/src/extension.ts, server/src/server.ts
Enable debug mode in the language server if `NG_DEBUG` is strictly
"true". This fixes issues where `NG_DEBUG=false` would enable debug
mode.
Closes #579
=> fix: enable debug mode only when it is strictly turned on

banner.rollup.config.js, rollup.config.js
Currently the rollup-ed banner file in dist/server/banner.js is included
in the release but it is unnecessary.
This commit moves it to server/out/banner/banner.rollup.js and thus removes
it from the dist folder.
=> build: move temp file for banner to server/out/banner

syntaxes/src/build.ts, syntaxes/src/template.ts, syntaxes/test/data/template.html.snap
Small PR to bring this grammar into feature parity with [my old extension](https://marketplace.visualstudio.com/items?itemName=dannymcgee.ng-html), which should be able to be deprecated and archived if this gets merged:
1. Added the asterisk prefix on structural directives to the match for `punctuation.definition.ng-binding-name.begin.html` (though I'm a little torn on whether `keyword.operator...` would actually be more accurate — any thoughts on that?)
1. Marked the attribute/property/directive name _as itself_ in the scope — e.g., the `ngClass` in `[ngClass]="..."` will be marked as `entity.other.ng-binding-name.ngClass.html` in addition to the less specific scopes already present.
This is similar to what the HTML grammar does, though it does it at the "meta" level (e.g., …
=> feat: more accurate and specific binding scopes

server/src/project_service.ts, server/src/session.ts
It appears that in some cases, a language service might not exist for a
project (https://github.com/microsoft/TypeScript/blob/d2c5d54242c69effbed0ebb27033047e0c995589/src/testRunner/unittests/tsserver/typingsInstaller.ts#L1951)
even if the `languageServiceEnabled` property on the project is `true`
(#557). To fix this, bail out of providing language service features
anytime a language service is not found by performing a strict null
check.
Closes #557.
=> fix: check that a language service exists for discovered projects

README.md
Adds information about the issue seen in #594 to the README. cc @ikilinc.
=> docs: add section about mismatch in TS loading the language service

server/src/session.ts
In https://github.com/angular/vscode-ng-language-service/pull/476 it was
incorrectly assumed that the content on disk is the most up-to-date
version. An unsaved buffer in the editor could be newer than the file on
disk and thus we should always load the script with the snapshot from
editor.
PR fix https://github.com/angular/vscode-ng-language-service/issues/632
=> fix: editor buffer out of sync with file on disk

scripts/build.sh
expression.json is currently not copied over to dist directory and hence
not in the prod build.
=> build: include expression.json in prod build

package.json
Inject the template syntax grammar to HTML derivative files (the scope
given to component HTML files) rather than just base HTML grammar. This
prevents the grammar being applied on more specific HTML syntaxes.
Closes #667
=> Apply Angular template grammar syntax only to HTML derivative files

.circleci/config.yml
We'll let it run for a couple PRs then remove Travis completely.
WIth this, we could also remove `scripts/install.sh` and `scripts/cleanup.sh`.
=> ci: Add .circleci/config.yml

server/src/project_service.ts, server/src/session.ts
This commit supresses diagnostic events sent by a project service
regarding changes to a project. Today, not supressing such events
can cause a type error to be thrown when the language server session
begins handling events for a file that is outside the project managed by
the project service, and for which a program does not exist in the
corresponding project's language service.
This commit also wraps blocks that terminate in setting a notification
status to always complete their notification.
Closes #693
Closes #696
=> Catch failure to open script when language service is disabled

server/package.json
Sets the package.json publishConfig to use the wombat-dressing-room
registry.
=> build: publish using wombat

scripts/cleanup.sh, scripts/install.sh
These two files can be removed now that we are no longer using Travis
CI.
=> ci: remove install.sh and cleanup.sh

server/package.json
"repository" field is needed for wombat proxy to check permissions.
=> build: add repository field to server/package.json

.gitignore
npmrc is used to store permission token for publishing to wombat proxy.
The token must never be checked in.
=> build: ignore .npmrc

README.md
https://github.com/angular/vscode-ng-language-service/issues/754
exprienced a versioning issue that isn't really explained well by the
README docs. Update the documentation with a better overview of how we
load packages and the suggested approach.
=> docs: update information about versioning language service and typescript

package.json, yarn.lock
typescript 3.9.5 contains latest bug fixes. Upgrading to latest before
investigating https://github.com/angular/vscode-ng-language-service/issues/824
=> chore: upgrade typescript to 3.9.5

scripts/format.sh, syntaxes/test/cases.json
#846 updated some JSON files. One of them was not formatted properly, but our CI failed to detect that.
There are multiple reasons:
1. The current format script skips over formatting checks if CI_MODE is true. (I wonder why we skip it in the first place?)
2. CircleCI was not setup to run the build-test workflow if PR is opened from a forked repo.
(2) is fixed by updating CircleCI config whereas (1) is fixed by this PR.
=> ci: report error if files are not formatted

DEVELOPER.md
This commit adds instructions to DEVELOPER.md to explain
1. How to bring up the developer instance of VSCode
2. Build and install local `@angular/language-service`
PR closes https://github.com/angular/vscode-ng-language-service/issues/854
=> docs: Add instructions for local development

scripts/format.sh
When running `yarn format` locally the CI check should not be triggered.
Run the formatting check only when "CIRCLECI" is present in the environment
variables.
`CIRCLECI` is a built-in environment variable that's always set according to
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
=> fix: run format check iff on CI

server/src/cmdline_utils.ts, server/src/server.ts, server/src/session.ts, server/src/tests/version_provider_spec.ts, server/src/version_provider.ts
This commit adds a hidden flag `--ivy` to load the Ivy version of
`@angular/language-service`.
This flag is hidden for now because it is only used for development.
The second entry point is resolved from `@angular/language-service/ivy.umd`
but in the next update it'll be `@angular/language-service/ivy` due to
the renaming done in https://github.com/angular/angular/pull/38086
=> feat: add --experimental-ivy flag for Ivy language service

package.json, server/src/version_provider.ts
This commit fixes a potential security vulnerability caused by the use of
require() to read a JSON file. If there is a JS file named `package.json.js`
in the node_modules, we would unknowingly execute the remote code while
trying to require() it.
Even though we only load `typescript` and `@angular/language-service`,
we cannot guarantee the content of these packages when they are installed
on users' machines.
Thanks @ddworken for reporting this issue and @koto for surfacing it to the
Angular team.
=> fix: do not use require() to read JSON files

integration/lsp/smoke_spec.ts, server/src/session.ts
As per https://microsoft.github.io/language-server-protocol/specification#workspace_workspaceFolders
, it's recommended that Language Servers that can work with multi-root
workspaces declare support for workspaceFolders.
For the angular language server, it's able to work with any file,
independently of the workspace root; so it's naturally able to work with
multiple roots.
Declaring support for workspaceFolders allows clients that use the
workspaceFolder heuristic as a way to decide of server instance
multiplicity (should it be a single instance or 1 instance per root) to
decide of starting only 1 instance of the LS. Without such information
from the LS, the client integration has to audit the LS, and force some
strategy to decide of the multiplicity, often in an hardcoded way; at
the …
=> Issue #909 - Explicit support for workspaceFolders

client/src/extension.ts, integration/project/.vscode/settings.json, package.json, server/src/cmdline_utils.ts
This commit adds a new configuration, `experimental-ivy` to turn on the
Ivy language service.
=> feat: add configuration for enabling Ivy

integration/project/app/app.module.ts, integration/project/app/foo.component.html, integration/project/package.json, integration/project/yarn.lock
Install `@angular/common` in the test project so that we could test
features like pipes.
`@angular/compiler` and `@angular/compiler-cli` are needed so that
we can run ngcc.
=> test: add @angular/common to test project

server/src/session.ts
This commit fixes a false alarm that says a config file cannot be found
when the language server tries to open a file for the first time.
We actually make two calls to `openClientFile()`.
1. In the first call, if the project doesn't already exist, the method
will create a project but it will not return the config filename.
2. In the second call, since the project has already been created,
the call to `openClientFile()` should succeed and we should receive a
config filename. If we don't receive one then it is an error, and we
should log message here instead of logging it in step (1).
=> fix: misleading error message about missing config when opening new file

integration/lsp/smoke_spec.ts, server/src/session.ts
See individual commits.
Commit 1: 
Refactor, create some helper functions for common code.
Commit 2: 
The Angular Language Service for Ivy will have a distinction
between "go to definition" and "go to type definition". We
need to add `typeDefinitionProvider` to the capabilities and call
`getTypeDefinitionAtPosition` when type definitions are requested.
=> feat: Add typeDefinitionProvider to capabilities

integration/project/tsconfig.json
This commit adds `angularCompilerOptions` for Ivy in the test project.
=> test: add angularCompilerOptions to test project

package.json
It seems that to get inline templates to be syntax highlighted with the
angular template grammar correctly, we not only need to include the
`template.ng` grammar pattern when matching an inline template (which
previously worked only for interpolations but would not seem to
correctly recognize template bindings); we also need to tell VSCode that
it should inject the template grammar in TypeScript files.
I cannot find a way to test this (since it differs from the TextMate
grammar tests, as this change instructs VSCode specifically how to add
the grammars), but screenshots attached to the PR for this commit
demonstrate before- and after-this-change syntax highlight on an inline
template. Furthermore non-template TypeScript should not be matched by
the template grammar, since the template …
=> Properly inject Angular template grammar in inline templates

syntaxes/expression.json, syntaxes/src/expression.ts, syntaxes/test/data/expression.html, syntaxes/test/data/expression.html.snap
The previous implementation of the template grammar for ternary
expressions would not match nested ternary expressions. In this commit
we update the matcher to use the TypeScript TM grammar's implementation
to do this correctly. Screenshots attached to the PR for this commit
demonstrate the change in a "real" template.
Closes #957
=> Properly parse nested ternary expressions

server/src/session.ts
We currently ask users to submit two logs when opening a new issue:
1. Logs from file, and
2. Logs from output channel (see screenshot below).
In order to simplify the workflow, we should log all console output to file
as well. This has two advantages:
1. We can piece together a more coherent picture by just looking at the log
file.
2. Users no longer have to submit logs from output channel.
Additional context: when debugging the integration test, I personally found it difficult to get a full understanding by just looking at the log file.
=> fix: log all console output to file

server/src/session.ts
This is a follow-up to https://github.com/angular/vscode-ng-language-service/pull/962
We should always call `Session.info()` or `Session.error()` to log entries
so that console entries also show up in log file.
=> refactor: use Session.info/error to log to console and output

integration/lsp/viewengine_spec.ts, server/src/session.ts
This commit fixes a bug whereby existing diagnostics in an external template
are not shown when the file is opened the first time. Diagnostics only show
up when subsequent edits are made to the file.
This is a regression after upgrading to TS 4.0
Fix https://github.com/angular/vscode-ng-language-service/issues/922
=> fix: LS not showing existing diagnostics on file open

common/tsconfig.json, integration/tsconfig.json
Since integration test is only used locally, building it in ES2017
helps debugging (less verbose JS output).
=> test: build integration test in ES2017

client/src/command-ngcc.ts, client/src/extension.ts, client/src/progress-reporter.ts, common/notifications.ts, server/src/session.ts
This commit implements the client-side work to support the ngcc feature.
The idea is as follows:
1. Client receives notification from server
2. Client runs ngcc
3. Client sends notification to server once ngcc is done
Watch screen recording [here](https://drive.google.com/file/d/1U1RpRD7SOKfx3E0uOjKh36LyqCkiSTiF/view?usp=sharing)
=> feat: client-side implementation for ngcc feature

integration/lsp/ivy_spec.ts, integration/lsp/test_utils.ts, server/src/server.ts, server/src/session.ts
Ivy compiler requires Ivy-specific properties generated by ngcc to be
available in the TS declaration files. As a result, the language service
will have to run ngcc on project load.
Since ngcc modifies node_modules, it should be run on the client side.
This commit implements the server-side code required to support ngcc.
The idea is as follows:
1. After a project has finished loading, the server sends a notification
to the client to run ngcc. Meanwhile, the server keeps the language
service disabled.
2. Client runs ngcc. Once complete, client sends another notification to the
server. Server re-enables language service.
=> feat: server-side implementation for ngcc feature

server/package.json, server/yarn.lock
Use `master` for the `next` version development, stable is now released
from `0.1100.x` branch
=> build: update @angular/language-service to v11.1.0-next.0

integration/lsp/ivy_spec.ts, scripts/test.sh, server/src/session.ts
This commit fixes a bug in which the program becomes unavailable after
the language service is re-enabled, resulting in a crash.
When the language service is disabled, the program gets discarded.
However, when the language service is re-enabled, the program is not
recreated.
This bug was difficult to reproduce because it was masked by the fact that
during normal startup, ngcc gets run, and in the process, ngcc generates a
lockfile named `__ngcc_lock_file__` in the `node_modules` directory.
This triggers the directory watcher, and through a long chain of events,
reloads the Configured project, therefore re-creating the program.
Without ngcc run (make it a no-op), the extension will crash because the
language service is unable to return the program.
=> fix: mark project as dirty after enabling language service

client/src/extension.ts
TS 4.1 introduced a breaking change in which `resolve` no longer has an
optional parameter, so by default, it must now be passed a value, or
an explicit type argument must be added.
See https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#resolves-parameters-are-no-longer-optional-in-promises
=> fix: explicitly type argument for Promise in TS 4.1

server/src/logger.ts, server/src/session.ts
Currently if users ask for logging to disabled (by not providing a filename
for the log file), the Logger defaults to writing to console.
In practice, this feature is not used at all. If users do not want logging,
then we should just disable logging entirely.
=> refactor: remove `traceToConsole` feature in Logger

integration/lsp/viewengine_spec.ts, server/src/session.ts
View Engine language service does not support `getTypeDefinitionAtPosition`.
See https://github.com/angular/angular/blob/3a6e7b5d2a54d011832191b96df5d8fd28a28740/packages/language-service/src/ts_plugin.ts#L113-L116
=> fix: enable type definition provider for Ivy only

client/src/commands.ts, client/src/extension.ts, common/initialize.ts, integration/lsp/viewengine_spec.ts, package.json, server/src/session.ts
Add a new command for opening the Angular log file right from the editor.
Screenshot of new command:
Screenshot of log file with highlighting:
Screenshot of failure:
Closes #990
=> feat: new command 'openLogFile' for opening log file from editor

integration/lsp/viewengine_spec.ts, server/src/session.ts
The Angular Language Service for Ivy will have a be able to provide
references for a template location so we need to add `referencesProvider` to the capabilities.
=> feat: add getReferencesAtPosition to capabilities

integration/lsp/ivy_spec.ts, server/src/session.ts, server/src/utils.ts
Currently, Ivy LS is not able to match external projects to their external
templates if no TS files are open. This is because Ivy LS does not implement
`getExternalFiles()`.
To fix this, we take a different route:
After ngcc has run, we send diagnostics for all the open files. But in the
case where all open files are external templates, we first get diagnostics
for a root TS file, then process the rest. Processing a root TS file triggers
a global analysis, during which we match the external templates to their
project.
For a more detailed explanation, see
https://github.com/angular/vscode-ng-language-service/wiki/Project-Matching-for-External-Templates
=> fix: match external templates to project on startup

scripts/build.sh
`semver` is a prod dependency of `vscode-languageclient`.
In the old build pipeline, `vscode-languageclient` is declared in
`client/package.json`.
When yarn installs dependencies in the `client` directory, it will put `semver`
next to `vscode-languageclient` in `client/node_modules`.
In the new build pipeline, `vscode-languageclient` is declared in root
`package.json`.
When yarn installs dependencies in the root directory, it chooses not to hoist
`semver`, instead puts it in a nested node_modules under
`node_modules/vscode-languageclient/node_modules`.
There is a bug in vsce that causes it to ignore nested `node_modules`,
resulting in a `vsix` build that is broken. The issue is tracked
[here](https://github.com/microsoft/vscode-vsce/issues/432), but it does not look like a fix will come …
=> build: use NPM to install node_modules

integration/tsconfig.json, syntaxes/test/driver.ts, tsconfig.json
The language server only supports node engine `>=10.9.0 <13.0.0`,
and according to https://node.green/ this version range fully supports
async/await, so we don't have to downlevel to es2015. This will make
the bundle smaller and faster. Also makes debugging easier.
https://github.com/angular/vscode-ng-language-service/blob/7fe63cbae86b1aa56df75dac96d7c008c16a4604/server/package.json#L12
=> build: output es2017

client/src/extension.ts
All dependencies are now listed in root node_modules, so we should not
resolve `@angular/language-service` from `server`.
=> fix: resolve @angular/language-service from root node_module

server/src/session.ts
TypeScript 4.0 added a new feature to provider smarter auto-imports,
(see https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#smarter-auto-imports)
but feature is not needed in Angular language service. We should turn this
off to improve performance.
=> fix: disable AutoImportProviderProject

client/src/extension.ts, client/src/progress-reporter.ts, common/notifications.ts, common/progress.ts, integration/lsp/ivy_spec.ts, scripts/test.sh, server/src/ngcc.ts, server/src/session.ts
This commit fixes a bug in which ngcc could not be resolved from the client
when the extension is running in the production vscode environment.
This is because internally, the client depends on `require.resolve` to look
for `ngcc` given the directory where the `tsconfig.json` is.
However, vscode provides its own [`require` mechanism][1], which is different
from Node.js. In particular, the bug is due to `require.resolve` not honoring
the `paths` parameter provided to the method. See Node.js [documentation][2] on
`require.resolve`.
We did not catch this bug because the custom `require` is not used
in the extension development host.
In order to mitigate this, we have a few options:
1. Use an external [`resolve` package][3] in the client to perform node module resolution
2. Bundle ngcc with …
=> fix: move ngcc operation to server

server/src/session.ts
For some reasons, the project could end up in an inconsistent
state where the language service is undefined. It could be that the project
is closed (?!). While we investigate this issue, put in a temporary fix
to force the project to reload.
Also note that the return type of getLanguageService() is deceiving,
because it could return undefined
https://github.com/microsoft/TypeScript/blob/1c1cd9b08d8bf1c77abb57d195cc6d79b1093390/src/server/project.ts#L797
=> fix: apply temporary fix to handle undefined language service

client/src/client.ts, client/src/commands.ts, client/src/extension.ts
Currently, when users change their vscode configuration (say when they enable
Ivy mode), they'll have to manually reload the window to force the new
configuration to take effect.
However, we cannot just start and stop the `LanguageClient` connection
because the server options passed to the client on startup is immutable.
To fix this, we wrap the `LanguageClient` in our own class
`AngularLanguageClient`, and reconstruct the server options every time the
server is restarted.
Code in `client/src/extension.ts` is copied to `client/src/client.ts` to avoid circular dependency between `extension.ts` and `commands.ts`.
=> fix: restart the server with new options on configuration change

scripts/test.sh
We should run `ngcc` before the test starts otherwise ngcc will run
during the LSP tests and potentially run into timeouts.
=> test: run ngcc before test starts

package.json
The extension now automatically runs ngcc on startup.
=> docs: No need to run ngcc before enabling Ivy

client/src/client.ts, integration/lsp/test_utils.ts, package.json, server/package.json, server/src/session.ts, yarn.lock
The following vscode-* packages need to be upgraded in one go:
- vscode-jsonrpc
- vscode-languageclient
- vscode-languageserver
- vscode-languageserver-protocol
This is due a [breaking change](https://github.com/microsoft/vscode-languageserver-node#3160-protocol-600-json-rpc-700-client-and-700-server) in the packages. Importing from the package root now pulls in `common` code only. In most cases, we want to import from `package/node` to include both common exports and NodeJS specific exports.
This upgrade requires vscode `^1.52.0`.
=> build: upgrade vscode-* packages to new major

server/src/session.ts
This is a follow-up to https://github.com/angular/angular/pull/40162.
In View Engine, `getExternalFiles()` returns a list of external templates
(HTML files), but we should not have marked them as `ScriptKind.External`.
As noted in https://github.com/microsoft/TypeScript/blob/b217f22e798c781f55d17da72ed099a9dee5c650/src/compiler/program.ts#L1897-L1899
`ScriptKind.External` should be used for external TypeScript files added
by plugins.
External templates should be marked as `ScriptKind.Unknown` instead.
=> fix: set external templates as ScriptKind.unknown

client/src/client.ts, server/src/session.ts
Re-enable language service even if ngcc fails, because users could fix the
problem by running ngcc themselves. If we keep language service disabled,
there's no way users could use the extension even after resolving ngcc issues.
On the client side, we warn users about potentially degraded experience.
Fix #1041
=> fix: do not disable language service if ngcc fails

scripts/build.sh, server/bin/ngserver, server/package.json
This commits add a `bin` field for the language server so that it can
be invoked as a standalone binary.
PR closes #1048
=> build: add bin field to package.json

client/src/client.ts, package.json
This commit adds a new configuration `angular.trace.server` to enable tracing
of the messages sent between the LSP client and LSP server.
This configuration is not used by Angular itself. Rather, it's read by the
`vscode-languageclient` package. See
https://github.com/microsoft/vscode-languageserver-node/blob/adb52f1276291b5bf8eaa97e053db8bb699b6872/client/src/common/client.ts#L3431
Once enabled, the request name, request duration, and optionally the request
payload will be logged to the Output console in vscode.
Example log:
```
[Trace - 3:58:03 PM] Received notification 'window/logMessage'.
[Trace - 3:58:03 PM] Received response 'initialize - (0)' in 777ms.
[Trace - 3:58:03 PM] Sending notification 'initialized'.
[Trace - 3:58:03 PM] Sending notification 'textDocument/didOpen'.
[Trace - …
```
=> feat: enable tracing of LSP messages and payload

server/bin/ngserver, server/src/version_provider.ts
1. fix: update min TS and NG versions
Angular v11.1 uses TS 4.0, these are the minimum version required for
the next release.
2. fix: ngserver script could not find index.js
index.js is located in the parent directory of ngserver.
=> Misc bug fixes

client/src/client.ts, server/src/cmdline_utils.ts, server/src/server.ts, server/src/session.ts
Provides a flag to turn off console logging completely.
This flag is different from `--logVerbosity`, which is used to control
the verbosity of logging to _file_.
Closes #584
=> feat: add --logToConsole flag

server/package.json
Adds support for Node 14, which is the latest Active LTS, according to
https://nodejs.org/en/about/releases/
(vscode is still on Node 12.14.x)
Close https://github.com/angular/vscode-ng-language-service/issues/1040
=> build: support Node 14

integration/lsp/test_utils.ts
Currently we spawn a new process for the language server for each test.
However, they are all kept alive. This PR fixes the resource leak by killing
the server after each test.
=> test: kill server instance after each test

server/src/session.ts
Currently, when a document is closed, we check to see if there are any other open
files in the associated project for that file. If not, we close the project (more
specifically, we close the _external_ project for the HTML files which releases
the inferred project and results in it being closed as well). If vscode, when
navigating between files, even of the same project, this can result in the
project being closed and then opened immediately because vscode closes
the currently open file before opening the next.
Instead, we wait to close "orphaned" external projects until after the
next file has finished opening. This way, we avoid closing and opening a
project when the two files are part of the same project.
Fixes  https://github.com/angular/vscode-ng-language-service/issues/1092
=> perf: delay closing of orphaned projects until next open

integration/lsp/ivy_spec.ts, integration/lsp/test_utils.ts, integration/lsp/viewengine_spec.ts, integration/project/app/app.component.ts, package.json, server/src/session.ts, yarn.lock
This commit adds rename capability to the Angular Language Service
extension. It's important to note that vscode only uses results from a
single rename provider. We cannot currently ensure that Angular takes
precedence over TypeScript when renaming from TS files
(see microsoft/vscode#115354) so this feature
is only available in _external_ template files (it is neither available for inline
templates nor other locations in TS files).
=> feat: Add renaming capability

.vscode/launch.json, client/src/client.ts, common/notifications.ts, integration/lsp/ivy_spec.ts, integration/lsp/test_utils.ts, package.json, server/src/session.ts, yarn.lock
This commit adds a prompt to encourage users turn on `strictTemplates` so
that they can get the most out of Angular language service.
PR close #1053
=> Suggest strict templates

server/src/ngcc.ts
ngcc progress is supposed to be reported to the client, but since the child
process is not silenced, stdio got inherited from the parent process. As a
result, ngcc progress shows up in the Output panel of Angular language service
instead of the status bar in vscode.
=> fix: ngcc progress not reported

client/src/client.ts, common/notifications.ts, integration/lsp/test_utils.ts, integration/lsp/viewengine_spec.ts, package.json, server/src/server.ts, server/src/session.ts, server/src/version_provider.ts
In order to drive adoption of the new Ivy Language Service before it
becomes the default in v12, this commit adds a prompt for users to
enable it if they are using `@angular/core` v9+.
Fixes #1095
=> feat: Prompt to use the Ivy Language Service if VE is detected

client/src/client.ts, client/src/commands.ts, client/src/providers.ts, common/requests.ts, integration/lsp/ivy_spec.ts, package.json, server/src/session.ts, server/src/utils.ts, server/src/version_provider.ts
This patch adds a command to retrieve and display the typecheck block
for a template under the user's active selection (if any), and
highlights the span of the node(s) in the typecheck block that
correspond to the template node under the user's active selection (if
any). The typecheck block is made available via a dedicated text
document provider that queries fresh typecheck block content whenever
the `getTemplateTcb` command is invoked.
Probably not something we want to land soon, but a useful debugging tool
for folks working with TCBs.
See also https://github.com/angular/angular/pull/39974, which provides
the language service implementations needed for this feature.
=> Command to view template typecheck block

package.json
Add a clarifying not about how to specifically override the global user
setting in a workspace for the ivy opt in.
fixes #1108
=> docs: clarify how to override ivy opt-in in a workspace

package.json, server/src/server.ts, server/src/server_host.ts, server/src/version_provider.ts, yarn.lock
In typescript 4.1.4, ts allows only package names as plugin names,
so `@angular/language-service/bundles/ivy` is disabled by ts. This
PR will resolve `@angular/language-service` to path `./bundles/ivy.js`
when the user enables the Ivy-native language service.
fixed #1109
=> fix: unable to load ivy native plugin

server/src/session.ts
Add check to ensure the returned language service for the project is the Angular
Language Service. This removes the need for a type assertion and also prevents
the native TS LS from taking the place of ours if there is an issue with the
plugin registration (which would result in duplicate results in TS files).
Fixes #1110.
=> fix: ensure project language service is the Angular LS

client/src/client.ts, integration/lsp/test_utils.ts, server/src/server.ts
`TSC_NONPOLLING_WATCHER` was used back in the early days to improve
file watcher performance, but it prevents files / directories from
being moved / renamed.
Since TS now provides built-in option to configure file watcher, this
environment variable is no longer needed.
See https://www.typescriptlang.org/docs/handbook/configuring-watch.html
Fix https://github.com/angular/vscode-ng-language-service/issues/750
=> fix: remove TSC_NONPOLLING_WATCHER env variable

package.json
This flag was accedentally changed to an array in
440a6c68e93e11d8b6c7f9001b3cb55a5e44dc66
It needs to be only a boolean so that it stays a checkbox in the UI.
=> fix: Revert back to boolean type for experimental-ivy flag

.vscode/launch.json
Move the command down so that the default command (first item) for
debugging is "Launch Client".
=> build: move 'Integration test: Attach to server' to third item

server/src/tests/version_provider_spec.ts, server/src/version_provider.ts
This commit fixes an inconsistency in resolving `typescript.tsdk` in the
Angular extension compared to native TypeScript extension.
In Angular, `require.resolve` is used to resolve `typescript.tsdk`, but
this does not work in environment that does not support node module
resolution (where `node_modules` directory does not exist).
The documentation for `typescript.tsdk` explicitly mentions the support
of providing the value as a fs path:
```
Specifies the folder path to the tsserver and lib*.d.ts files under a
TypeScript install to use for IntelliSense, for example:
./node_modules/typescript/lib.
```
=> fix: attempt to resolve tsdk using fs path

integration/lsp/test_utils.ts
When the `.vsix` file is built, prod dependencies are installed in `dist/npm`.
The LSP tests should resolve `typescript` from `node_modules` in that
directory instead of package root to make sure prod build is tested with
prod dependencies.
=> test: use TS dep installed for production

client/src/client.ts, client/src/commands.ts, common/requests.ts, integration/lsp/ivy_spec.ts, package.json, server/src/session.ts, server/src/version_provider.ts
This commit adds a command to locate the components which reference a
given external template via their `templateUrl`s. If there is only one
component, immediately navigate to the component class declaration. If
there are multiple components, show them each in the same manner as
"find references" would.
=> feat: add command to go to component(s) from external template

package.json
Go to component should not be shown in TypeScript files.
=> fix: show Go to component in HTML files only

server/src/ngcc.ts
ngcc process will fail if the debugger is already attached to the main
process because it inherits `execArgv` from the parent process by
default.
=> fix: do not pass execArgv to ngcc process

integration/lsp/ivy_spec.ts, integration/lsp/test_utils.ts, server/src/server_host.ts
It turns out typecheck files are not retained even after the fix in
https://github.com/angular/angular/pull/40162.
For a complete explanation of the situation, see prior issue:
https://github.com/angular/vscode-ng-language-service/issues/1030
This is because even after adding the typecheck files to the list of
files to retain, tsserver will still remove them from a project if they
do not exist on disk:
https://github.com/microsoft/TypeScript/blob/3c32f6e154ead6749b76ec9c19cbfdd2acad97d6/src/server/editorServices.ts#L2188-L2193
In order to force tsserver to retain the files, we need to fake their
existence. This is done in the `ServerHost`.
Admittedly, this is not a great fix because it relies on the knowledge
of the typecheck file suffix, which is an implementation detail in the compiler. …
=> fix: retain typecheck files after project reload

package.json, server/package.json, server/src/server.ts, server/src/server_host.ts, server/src/session.ts, server/src/tests/version_provider_spec.ts, server/src/version_provider.ts, yarn.lock
Starting from `@angular/language-service` v12.0.0-next.3, the package
will dynamically load View Engine or Ivy LS based on the config passed
to the plugin.
This reverts https://github.com/angular/vscode-ng-language-service/pull/1111
=> fix: use single entry point for @angular/language-service

server/src/server.ts, server/src/session.ts
This commit checks if `typescript` is resolved to the tsdk in google3,
and if so set `ivy` and `strictTemplates` to true. Both settings are
required for the Angular extension to work in google3.
=> fix: force enable Ivy and strictTemplates in google3

server/src/server.ts, server/src/server_host.ts, server/src/session.ts
In google3, all the dependencies of a TypeScript program are known ahead
of time and they are listed in `tsconfig.json`. For this reason, there
is no need to watch `node_modules` directory. Tsserver in google3 has
additonal patch that explicitly prohibits watching directories that start
with `/google/src`.
This was not detected during development because we did not actually use
the TypeScript module specified in `typescript.tsdk`. The dynamic
loading of the `typescript` module requires the server code to be
compiled in AMD first, which happens only during the production build.
=> fix: do not watch directories in google3

client/src/commands.ts, package.json, server/src/server.ts
For large projects (especially projects in google3), logging to file with
will slow down the language service because it prints all the filenames in
the project. This is true even when the logging verbosity is `terse` (the
old default).
This PR turns off logging by default. If users want to inspect the logs,
they can run the `Open Angular server log` command, which will automatically
set the log verbosity to `verbose` and restart the server.
=> fix: turn off logging by default

server/src/server.ts, server/src/tests/version_provider_spec.ts, server/src/version_provider.ts
Starting from v12.0.0-next.3 `@angular/language-service` provides a single
point, so the `ivy` flag is no longer needed when resolving the package.
=> refactor: ivy flag no longer needed with single entry point

server/src/server_host.ts, server/src/session.ts
Users can specify any arbitrary plugins in their `tsconfig.json`, and
tsserver will load all of them by default. In Angular server, we do not
want this behavior since other plugins can slow down the server
considerably. Angular server should only load
`@angular/language-service`.
In google3, `@bazel/tsetse` and `ide_performance` plugins are automatically
added by the `ts_config` rule.
=> fix: do not load plugins except @angular/language-service

server/src/ngcc.ts, server/src/version_provider.ts
ngcc v11.2.4 and above supports `--typings-only` mode, which updates the
TypeScript declaration files but keep Javascript files unmodified.
This will speed up ngcc operation in the extension.
cc: @petebacondarwin
=> refactor: run `ngcc --typings-only` if version >= 11.2.4

.github/workflows/lock-closed.yml
Update to use the latest lock closed sha, additionally use the full length sha for
referencing the exact version to use.
=> build: update the lock closed sha to the latest sha

server/src/session.ts, server/src/utils.ts
This commit contains a few perf improvements:
1. Increase debounce time from 200ms to 300ms
This increases the likelihood of consolidating diagnostics requests, but
should have little impact on user perception.
2. While in the middle of a diagnositc check, stop the operation if there is
another pending diagnostic request.
3. After checking a file, yield the execution thread so that the server gets
a chance to process incoming requests.
=> perf: yield after checking diagnostics for an open file

.vscode/launch.json, client/src/client.ts, client/src/embedded_support.ts, client/src/tests/embedded_support_spec.ts, client/src/tests/tsconfig.json, client/tsconfig.json, jasmine.json, package.json, yarn.lock
…gular context
The Angular Language Service extension of vscode has several pieces to
it:
* The client, which communicates directly with vscode
* The server, which handles LSP requests over an lsp connection
* @angular/language-service which provides concrete answers to LS queries
We added an optimization the @angular/language-service which exits early
when a request is outside the Angular context. This prevents unnecessary
Angular analysis of a file when we know from the start that there are no
Angular-specific results at a location.
This commit provides an additional optimization by adding a similar preventing
short-circuit from the client side. This prevents requests from even
being sent to the server when we know there is no Angular information at
a location. This optimization is a …
=> perf: prevent requests from being sent to the server when outside Angular context

integration/lsp/ivy_spec.ts, server/src/session.ts
This commit adds a codelens which provides a link to the component(s) of
an external template.
=> feat: Add codelens with a link to go to the component from a template

client/src/client.ts, server/src/logger.ts
Logger should print a single timestamp for each "group" entry.
Also, logging verbosity in dev mode should respect `angular.log`.
=> fix: logger should print one timestamp for an entire group

.vscode/launch.json
Disable all non-native extensions when bringing up the dev instance.
=> build: disable other extensions while testing

integration/lsp/ivy_spec.ts, integration/lsp/viewengine_spec.ts, server/src/session.ts, server/src/tests/utils_spec.ts, server/src/utils.ts
This commit reduces the number of `getSemanticDiagnostics` calls the server
makes by looking at the file type when a file is opened /changed.
If the file is an external template, we know it has to be local to a
particular component, so checking that one file is sufficient.
If the file is TypeScript, then we compute diagnostics for all open files.
(idea: If we can detect that changes are made only to inline template, then
we could skip checking other open files altogether).
=> perf: optimizations to reduce and prioritize getSemanticDiagnostics for open files

esbuild.js
When switching from rollup to esbuild, we enabled minification of
the client code for the first time. This ended up breaking the
extension on Windows machines. This commit removes the minification
and should resolve the broken activation on Windows.
Fixes #1198
=> fix: do not minify the client code

integration/e2e/index.ts, package.json, yarn.lock
`vscode` package has been deprecated:
https://www.npmjs.com/package/vscode
It is replaced by `@types/vscode`:
https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest
This fixes the problem with GITHUB_TOKEN when the typings are downloaded
via postinstall script.
Note: the types must be in sync with the `vscode` engine specified in `package.json`.
This check is enforced by `vsce`, but we should be aware of this when updating versions.
=> build: replace vscode package with @types/vscode

client/src/client.ts, client/src/extension.ts
fix: only restart language server on angular configuration change
Currently, we stop and start the client on _any_ configuration change.
With this commit, we will only do that when the changed configuration
affects the `angular` section.
fix: dispose reporters and notification handlers when client is stopped
The "restart Angular Language server" command as well as the restart
that happens when a configuration changes stops and starts the client.
We should track and clean up the notification and progress handlers for
the client at this time rather than continually pushing new ones to the
vscode context, which is only cleaned up when the window reloads/closes.
Fixes #1232
=> fix: dispose reporters and notification handlers; fix: restart only on angular config change

.circleci/config.yml, scripts/test.sh
Use CircleCI config to install node_modules in `integration/project` and
`integration/workspace` so that they are cached.
=> ci: cache node_modules in test project and test workspace

.github/workflows/node.js.yml, integration/e2e/definition_spec.ts, integration/e2e/helper.ts, scripts/e2e.sh
Run E2E test on Linux and MacOS.
(Test currently fails on Windows, further debugging required).
Ref https://code.visualstudio.com/api/working-with-extensions/continuous-integration
=> Create node.js.yml for E2E test on GitHub Actions

server/src/session.ts
CodeLens will show "!!MISSING: command!!" on startup while ngcc is
running (because the language service gets disabled). Fortunately, the
CodeLensResolve gets called periodically so we can simply wait until the
language service is re-enabled before returning the resolved command.
Fixes #1253
=> fix: do not resolve CodeLens command until LS is enabled

.vscode/launch.json
`Launch Client` has been renamed to `Launch Dev Client`.
=> build: fix compound target in launch.json

client/src/client.ts, common/requests.ts, integration/lsp/ivy_spec.ts, server/src/session.ts
=> perf: Avoid making Angular-related decisions for files not in an Angular project

client/src/client.ts, integration/lsp/test_utils.ts, integration/project/.vscode/settings.json, package.json, server/src/cmdline_utils.ts
Ivy LS will be the default in Angular v12.
To revert to legacy View Engine LS, enable the `view-engine` option:
=> fix: make Ivy LS the default

.github/workflows/node.js.yml
Run `ngcc` prior to starting vscode instance
=> ci: fix flaky e2e test

server/src/server.ts
`server.js` is a script, which means when it's bundled all symbols defined
in the root scope of the file show up as globals.
Wrap them in main() function to avoid polluting the scope.
=> refactor: wrap server script in main() to avoid polluting globals

client/src/client.ts, integration/lsp/ivy_spec.ts, package.json, server/src/session.ts, server/src/utils.ts, yarn.lock
This commit adds support for signature help to the LS extension, by
translating from the TS `getSignatureHelpItems` API into LSP.
=> feat: add support for signature help

server/src/server_host.ts
The options are needed so that the server respects the `WatchOptions`
provided by users in their tsconfig.json.
```ts
export interface WatchOptions {
watchFile?: WatchFileKind;
watchDirectory?: WatchDirectoryKind;
fallbackPolling?: PollingWatchKind;
synchronousWatchDirectory?: boolean;
excludeDirectories?: string[];
excludeFiles?: string[];
[option: string]: CompilerOptionsValue | undefined;
}
```
Without this fix, the server falls back to file polling, which consumes considerable CPU cycles in large projects.
fix https://github.com/angular/vscode-ng-language-service/issues/636
=> fix: pass watch options to watchFile and watchDirectory

client/src/client.ts
`context.logPath` has been deprecated, use `context.logUri` instead.
=> refactor: replace logPath with logUri

client/src/client.ts, common/notifications.ts, integration/lsp/viewengine_spec.ts, server/src/session.ts
Now that Ivy LS is the default in version 12, `SuggestIvyLanguageService` notification
is no longer needed.
=> refactor: remove suggest Ivy LS notification

.gitignore
adds *.swp and *.swo files to .gitignore to avoid versioning temorary
files created by vim. This aligns this repo with angular/angular.
See implementation in angular/angular: https://github.com/angular/angular/blob/master/.gitignore#L21
=> chore: add vim swap files to .gitignore

client/src/client.ts, client/tsconfig.json, common/resolver.ts, common/tests/resolver_spec.ts, common/tests/tsconfig.json, jasmine.json, package.json, server/banner.tsconfig.json, server/src/ngcc.ts, server/src/tests/version_provider_spec.ts, server/src/version_provider.ts, test.tsconfig.json
Move the version resolver code to `common` directory so that it can be shared with client code.
=> refactor: move version resolver to common

client/src/client.ts, integration/lsp/test_utils.ts, server/src/server.ts, server/src/session.ts
patch version of #1323
`TSC_NONPOLLING_WATCHER` was used back in the early days to improve
file watcher performance, but it prevents files / directories from
being moved / renamed.
Since TS now provides built-in option to configure file watcher, this
environment variable is no longer needed.
See https://www.typescriptlang.org/docs/handbook/configuring-watch.html
The watch options used are derived from the user defined options in
their `tsconfig` combined with the default options provided to the
project service via `setHostConfiguration`
([code reference](https://github.com/microsoft/TypeScript/blob/f7ef1540d3c10fb282d1d433d9f2850b28391169/src/server/editorServices.ts#L2985-L2989)).
As noted in the documentation for configuration watch options, the
default when no watch options are …
=> fix: remove TSC_NONPOLLING_WATCHER env variable and provide default watchOptions

client/src/client.ts
I have observed that the performance enhancement introduced in #1272 does not
work in some situations. It appears that if I attempt to do operations in an
external template before the language service is initialized, the template will
be identified as not being inside an Angular project.
The result of this incorrect determination is that we will not service
requests for that file. This commit disables the check by always returning
`true`, effectively marking every TS and HTML file as being inside an
Angular project.
There may be some performance degradation in non-Angular projects as a
result due to additional file tokenization of TypeScript files. However,
we do still expect this tokenization to be very fast and there should be
no observable performance issues. …
=> fix: files incorrectly determined as not being in an Angular project

client/src/client.ts, client/src/embedded_support.ts, integration/lsp/ivy_spec.ts, server/src/session.ts
Previously we had decided to disable renaming in TypeScript files
because of a limitation in VSCode
(https://github.com/microsoft/vscode/issues/115354). This meant that we
could give consistent expectations for Angular renames: they only work
in external templates.
This change updates that expectation by providing the ability to rename
from strings in TypeScript files. Because TypeScript would not
provide any rename results for most strings (see note below), we can be sure that
Angular will be asked to provide its rename results for these cases.
Additionally, this moves the logic for determining if we should provide
renames outside the server. The benefit of this is that potential
consumers of the @angular/language-server for other editors would be
able to provide renames if they do not …
=> feat: Allow renaming from string literals in TS files

client/src/client.ts
This commit fixes a bug where View Engine is not launched even though
the Angular version is resolved correctly. This is because the configuration
value is typed as "boolean", and defaults to `false` when the value is not set.
Fix #1350
=> fix: check Angular version if angular.view-engine is false

server/src/session.ts
The log message is misleading because LS is enable even if ngcc fails.
=> fix: remove message about disabled LS if ngcc fails

README.md, client/src/client.ts, package.json
This configuration does not work well in practice because we cannot guarantee
the compatibility between the extension and an older version of
`@angular/language-service`.
If users have to revert to an older version for any reason, they should
download an older extension from the VSCode marketplace.
Close #1325
=> fix: remove angular.ngdk configuration

client/src/client.ts, integration/e2e/completion_spec.ts, integration/e2e/helper.ts, integration/e2e/hover_spec.ts, integration/project/app/foo.component.html
Our client-side middleware retrieves html provider completions for
inline templates because the template string is not otherwise detected
as HTML by the registered HTML providers. We should only create this
virtual document and retrieve HTML provider results for typescript
files.
Fixes #1357
=> fix: only give html provider completions for inline templates

server/src/session.ts
Because 12.0.x and master diverged a little for renaming implementation
the change to return null instead of undefined caused a build error in
the patch branch.
=> fix: bad merge caused build failure

integration/lsp/ivy_spec.ts, integration/lsp/test_utils.ts, integration/project/app/app.component.ts, server/src/completion.ts, server/src/session.ts
The `TextEdit` is not meant to replace text to the right of the
position. Instead, `InsesrtReplaceEdit` should be used.
Reference discussion in LSP issue for examples on replacement vs
insertion range for `InsertReplaceEdit`:
microsoft/language-server-protocol#846
Fixes #1388
Note that the issue did not appear in the VE version of the extension
because it was only providing completions as inserts (they had
no `replacementSpan`).
=> fix(completions): fix completions for inputs / outputs

package.json
Our extension does not support untrusted workspaces because it executes
`ngcc` from `node_modules`.
See https://github.com/microsoft/vscode/issues/120251 for a description
of workspace trust and how to determine if an extension should support
untrusted workspaces.
Fixes #1322
=> feat: add configuration for workspace trust

client/src/client.ts
The command to restart the language server calls `client.stop` followed
by `client.start`. We should clear the caches so that the restart
command starts with a clean state.
=> refactor: clear client caches on stop request

integration/e2e/helper.ts
Rather than waiting a set 20 seconds for ngcc to finish, this updates the tests to
instead wait for definitions to be available in the template. This change was intended
to be in #1367 but accidentally was reverted before merging
=> test: update e2e test wait condition to wait for definitions

integration/lsp/ivy_spec.ts, server/src/completion.ts, server/src/session.ts
From the spec:
>Most editors support two different operations when accepting a completion
>item. One is to insert a completion text and the other is to replace an
>existing text with a completion text. Since this can usually not be
>predetermined by a server it can report both ranges. Clients need to
>signal support for InsertReplaceEdits via the
>textDocument.completion.completionItem.insertReplaceSupport client
>capability property.
Fixes #1451
=> fix(server): Only provide InsertReplaceEdit when the client supports it

server/src/session.ts
After `ngcc` finishes, only enable language service for projects that
are open. This avoids an error that would otherwise be thrown by TypeScript.
It's not entirely clear what causes the project to close immediately
after opening, but it appears to be triggered by having files open from
multiple projects. The files not actively being displayed in the editor
have their projects closed, but this also only appears to happen after
having the editor open for a long time.
Fixes #1438
Fixes #1399 - Not entirely sure this fixes the issue there, but it may
and we don't currently have any other indicators for what the issue
there might be if the cause is different.
=> fix(language-server): Only enable language service on open projects

integration/e2e/helper.ts
This change is an effort to reduce the flakiness of the e2e tests on macos.
If those e2e tests are still still flaky after this change, we should consider them for macos.
example failure due to timeout: https://github.com/angular/vscode-ng-language-service/runs/3186857720
=> test: update default timeout inteval to 30 seconds

client/src/client.ts, integration/lsp/ivy_spec.ts, integration/lsp/test_utils.ts, integration/lsp/viewengine_spec.ts, integration/project/tsconfig.json, package.json, server/package.json, server/src/cmdline_utils.ts, server/src/completion.ts, server/src/server.ts, server/src/session.ts, yarn.lock
wait for [PR](https://github.com/angular/angular/pull/42995) to land
=> feat: add config to enable auto-apply optional chaining on nullable symbol

server/src/session.ts
Update return types of functions to:
* Explicitly have `void` as the return type
* Prefer `null` over `undefined`
The LSP spec always uses `null` as the return types:
https://microsoft.github.io/language-server-protocol/specifications/specification-current/
In fact, if the server is configured to return `undefined`, it will
still be `null` after coming through the LSP connection. To avoid any
confusion, we should just always use `null`.
=> refactor(server): Prefer `null` over `undefined` and explicit `void`

.circleci/config.yml, integration/lsp/ivy_spec.ts, integration/lsp/test_utils.ts, integration/project/package.json, integration/project/yarn.lock, integration/test_constants.ts, integration/workspace/package.json, integration/workspace/yarn.lock, package.json, scripts/build.sh, scripts/test.sh, server/src/ngcc.ts, server/src/session.ts, server/src/tests/ngcc_spec.ts, server/src/version_provider.ts, yarn.lock
=> refactor: update to angular v13 with APF v13 output

.circleci/config.yml, .github/workflows/node.js.yml, scripts/build.sh
Use a scheduled job to check the repository against the latest version of @angular/language-service from
https://github.com/angular/language-services-builds
=> ci: setup scheduled CI job to test repository against the latest builds

scripts/test.sh
When running tests against the builds repo, the package.json and yarn.lock files get updated.
The syntax check only really cares about modifications to files in the syntaxes folder.
=> test: fix syntax tests so they work when testing against builds repo

client/src/client.ts, package.json
Angular v13+ projects do not support VE. If the client detects a v13+ project in the workspace,
it now sets legacy VE to false, regardless of the extension options or incompatible legacy projects
in the workspace.
=> fix: Prevent legacy VE from being used with v13 projects

package.json, server/package.json, yarn.lock
Updating the node version from 14 to 16 makes the release process harder. The v12 language service is required to support legacy view engine. When installing that dependency, we need to use node 14.
=> build: revert updating node version

server/src/session.ts
When the user tries to go to the definition that is in the DTS file,
the Angular LS will map it to the original source file. Because of
not updating the `scriptInfo`, the Angular LS returns the wrong range
of the definition.
=> fix(server): return the right range for the original source file of DTS

client/src/client.ts, override_rename_ts_plugin/README.md, override_rename_ts_plugin/index.js, override_rename_ts_plugin/package.json, package.json, scripts/build.sh, yarn.lock
This PR will add a new package that is applied to the built-in TS
extension by the config [`typescriptServerPlugins`][1] and is used
to disable rename provider of the built-in TS extension so VSCode
asks the Angular Language Service for the answer instead.
Detail about this package is [here][2].
[1]: https://code.visualstudio.com/api/references/contribution-points#contributes.typescriptServerPlugins
[2]: https://github.com/angular/angular/blob/master/packages/language-service/README.md#override-rename-ts-plugin
=> feat(extension): Support renaming from TypeScript files

client/src/client.ts, package.json, server/src/cmdline_utils.ts, server/src/server.ts, server/src/session.ts
Running ngcc is required for gathering metadata information of libraries
not published with Ivy instructions. However, ngcc can also be run
manually _outside_ of the extension. Developers may often be running a dev
server which does this step so doing it in the extension as well is
redundant. In addition, there have been issues with running it in VSCode
(#1353, #1444, and potentially other Nx related issues).
This option gives developers the ability to manually opt out of running
ngcc from the extension if it is proving to be problematic for their
setup.
Fixes #1353
=> feat: Add option to disable ngcc

client/src/client.ts, client/src/commands.ts, common/requests.ts, package.json, server/src/cmdline_utils.ts, server/src/server.ts, server/src/session.ts
Adds a command to manually run ngcc for a given file. This commit also
refactors the `disableNgcc` option to indicate that it's disabling the
_automatic_ `ngcc` run but it can still be triggered manually with the
new command.
The `disableAutomaticNgcc` option and new command to manually run ngcc
are complementary. We have found that the extension can be overzealous
in automatically running ngcc, especially with solution-style project
configurations (common practice in Nx projects). If a dev server is not
active to rerun ngcc when needed, then the new command gives an easy way
to do that when the `disableAutomaticNgcc` option is set.
Fixes #991
=> feat: add command to run ngcc manually

syntaxes/src/template.ts, syntaxes/template.json, syntaxes/test/data/template.html, syntaxes/test/data/template.html.snap
The previous syntax regex capture did not allow a % symbol at all. This
commit updates the regex to allow the property binding and binding name
to be terminated by 0 or 1 '%' characters.
Fixes #1619
=> fix: Correct syntax highlighting for style.prop.%

.circleci/config.yml, .github/workflows/node.js.yml, .github/workflows/scorecard.yml
Applies changes for the `DIRECT` phase of the renaming
master to main planning doc.
cc. @josephperrott
=> build: changes for primary branch rename to main

client/src/client.ts, package.json, server/src/cmdline_utils.ts, server/src/server.ts, server/src/session.ts
This feature request is to provide an extension option to override the project's
`angularCompilerOptions`. This would allow the language service to enable `strictTemplates`.
With the release of v12, the Ivy-based Language Service became the default.
With that, the information provided by the extension follows what the application
has configured the compiler to interpret (see Alex's
[blog post](https://blog.angular.io/under-the-hood-of-the-language-service-ab763c26f522)
for more information on why this was done). As a result, developers upgrading from
previous versions that have apps which do not have strict templates enabled often
experience a loss of information from the extension. It also may not be feasible
for large projects to enable `strictTemplates` immediately due to an abundance …
=> feat(extension): Add option to force strict templates

CHANGELOG.md, README.md, override_rename_ts_plugin/README.md, package.json, syntaxes/README.md
Cleans up all references to the old `master` branch.
=> build: clean up references to old `master` branch

README.md
Renaming the branches broke the gif link in the patch branch
=> fix(docs): Fix the link to the demo after branch rename

server/src/session.ts
In v14, the .d.ts file for angular core is now "index.d.ts" rather than "core.d.ts".
fixes #1657
=> fix(language-server): Fix detection of Angular for v14+ projects

client/src/client.ts, override_rename_ts_plugin/README.md, package.json, scripts/build.sh, yarn.lock
This is a rollback of #1589 due to breaking rename scenarios in
projects.
https://github.com/angular/vscode-ng-language-service/issues/1683#issuecomment-1148816800
Fixes https://github.com/angular/vscode-ng-language-service/issues/1685
=> fix(extension): disable rename override to allow built in TS renaming

integration/lsp/ivy_spec.ts, package.json, server/package.json, server/src/session.ts, server/src/utils.ts, yarn.lock
In ts service, the
`codeFixes`([getCodeFixesAtPosition](https://github.com/microsoft/TypeScript/blob/7584e6aad6b21f7334562bfd9d8c3c80aafed064/src/services/services.ts#L2689))
and
refactors([getApplicableRefactors](https://github.com/microsoft/TypeScript/blob/7584e6aad6b21f7334562bfd9d8c3c80aafed064/src/services/services.ts#L2699))
are resolved in different request. But in LSP they are resolved in the `CodeAction` request.
Now, this PR only handles the `codeFixes` because the `@angular/language-service` only supports it.
=> feat(server): support code action

client/src/client.ts
The dev bundle mapping was broken in
https://github.com/angular/vscode-ng-language-service/commit/69fad33204474930d0fa867c5e23c82041a91dc6
but is trivially fixed with this update.
=> build: fix dev bundle location after updating source paths

jasmine.json, server/src/tests/ngcc_spec.ts
The jasmine spec paths were broken in
https://github.com/angular/vscode-ng-language-service/commit/69fad33204474930d0fa867c5e23c82041a91dc6
but is trivially fixed with this update.
=> test: fix jasmine spec_files paths after updating source paths

server/src/ngcc.ts
Uses indexOf instead of lastIndexOf in resolveAndRunNgcc.
This resolves the case where a user is using pnpm and ngcc is resolved through symlinks to a deeply nested virtual store node_modules location:
`some/user/path/node_modules/.pnpm/@angular/compiler-cli@1.2.3/node_modules/@angular/compiler-cli/...`
lastIndexOf would resolve to `some/user/path/node_modules/.pnpm/@angular/compiler-cli@1.2.3` which is incorrect. indexOf gets you to the desired `some/user/path`
=> fix: support deeply nested pnpm virtual store node_modules paths in resolveAndRunNgcc

.circleci/config.yml
The job is causing a break on an upgrade PR https://github.com/angular/vscode-ng-language-service/pull/1749
=> Disable bazel-build-and-test CircleCI job; not yet load bearing

package.json, server/package.json, yarn.lock
This update is necessary to fix [an issue](https://github.com/angular/vscode-ng-language-service/issues/1746) in which the language service reports phantom errors, due to some [changes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#decorators-are-placed-on-modifiers-on-typescripts-syntax-trees) in the way TS handles decorators.
=> build: update to TS 4.8.2 and Angular 14.2.0.

.bazelrc, BUILD.bazel, package.json, scripts/build.sh, server/BUILD.bazel, version.bzl
The package/project version should be managed via the `package.json` file so that existing tooling like `yarn ng-dev` does not break with the recent Bazel migration. Tools like `ng-dev` expect a project version to be present in the top-level `package.json`. The current placeholder breaks the release and branching expectations.
=> build: do not manage package version in Starlark file

scripts/build.sh
There is no reason to copy files to the dist folder anymore with bazel. Update the build.sh to clean up previous builds by running 'bazel clean'.
=> build: update build.sh script for bazel

WORKSPACE, package.json, yarn.lock
For some reason, npm couldn't resolve `"@angular/language-service": "15.1.0-next.0"` so I changed it temporary to `"@angular/language-service": "15.0.0"` so CI could run
=> chore: update to the latest Aspect rules_js, rules_ts, rules_jasmine & rules_esbuild

.vscode/tasks.json
The task end pattern was only configured to support single digit tasks
=> testing: fix task endPattern for iBazel

.bazelrc, .gitignore, WORKSPACE
Part of fix for #1815.
This is safe to land before any of the other fixes required do as it doesn't change anything here. Fix won't be in effect until rules_js & angular PRs land and this repo is updated to a release of rules_js that includes the its fixes.
See issue for details.
=> fix: fix "install local @angular/language-service" workflow under Bazel build

.bazelrc
This flag should only be set for the `bazel test` command
=> build: fix .bazelrc --build_test_only flag

WORKSPACE
Looks like this regressed at some point. The //:npm target fails to build with
```
ERROR: /Users/greg/aspect/google/vscode-ng-language-service/BUILD.bazel:34:12: Copying files to directory failed: missing input file '//:node_modules/vscode-nls'
ERROR: /Users/greg/aspect/google/vscode-ng-language-service/BUILD.bazel:34:12: Copying files to directory failed: 1 input file(s) do not exist
```
at HEAD without this fix
=> build: add missing vscode-nls to npm_translate_lock hoisted package

.bazelignore, WORKSPACE, pnpm-workspace.yaml, v12_language_service/BUILD.bazel
Stacked on top of https://github.com/angular/vscode-ng-language-service/pull/1825 which should land first
=> fix: add v12_language_service/node_modules to release package

server/src/session.ts
Now the Angular code action provider only supports `QuickFix`. If leave the `codeActionKinds` empty, all action requests will be sent to the Angular language service, especially for the action before saving the file, the Angular code action provider will try to fix all errors in the whole file, it's expensive.
Fixes #1828
=> fix(server): filter unsupported code action

WORKSPACE
New token is within `data` now.
@dylhunn @atscott Adding a new token here so the old one still works until it is not needed anymore. Old one (`PLACE_HOLDER_FOR_packages/language-service/build.sh_IN_angular_REPO`) can be removed anytime if it is not needed.
=> build: update angular/angular packages/language-service/build.sh placeholder

client/src/client.ts, package.json, server/src/cmdline_utils.ts, server/src/server.ts, server/src/session.ts
Code actions require additional analysis and developers may want to disable them for performance reasons.
Resolves #1840
=> feat: Add option to disable code actions

client/src/client.ts, package.json, server/src/cmdline_utils.ts, server/src/server.ts, server/src/session.ts
This reverts commit 3453361c15ca2e98bea54172ff80bffc0736ae8b.
This feature was only added as a potential mitigation for performance issues in the v15 release. These performance issues have been unreproducable by the team and disabling quick fixes using this feature has not been confirmed to resolve the problem from developers expeiencing the issue.
=> Revert "feat: Add option to disable code actions (#1849)"

integration/lsp/test_utils.ts, server/src/session.ts
If the client doesn't explicitly tells the server that they have this capability then a `Location` should be send instead of `LocationLink` as a reply to a "Goto Definition Request".
See the relevant documentation:
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_definition
Closes #1874
=> Respect the client capability "textDocument.definition.linkSupport."

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, WORKSPACE, package.json, pnpm-lock.yaml, server/src/session.ts, server/src/version_provider.ts, yarn.lock
The bundled TS version should match the upstream repository whenever possible.
=> build: update bundled TS version to match upstream Angular

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, package.json, server/src/cmdline_utils.ts, server/src/completion.ts, server/src/server.ts, server/src/session.ts
This commit removes the references to the Ivy option, as it's not supported anymore. This also adds
more documentation to the help message to cover new features since the help message was
last updated.
=> refactor(server): Remove references to Ivy and improve help message docs 

server/src/server.ts
This commit reorders the import statements os the parseCommandLine import happens before calling the function. When working in debug mode, the current ordering fails.
=> build: reorder imports so debug mode works correctly

client/src/embedded_support.ts, client/src/tests/embedded_support_spec.ts
This probably still has its own issues but seems to be at least an improvement over past scanner issues.
It may be good to spend more time on the correctness of this or just `ts.createSourceFile`. This previously wasn't done due to perfomance concerns.
fixes #1872
=> fix(client): fix detection of Angular context after string interpolation

server/package.json
The test package is only used for, you guessed it, tests and should not be in the regular deps
resolves #1927
=> build: Move 'test' package to dev dependencies

client/src/client.ts, client/src/commands.ts, common/initialize.ts, server/src/session.ts, server/src/tests/text_render_spec.ts, server/src/text_render.ts
https://github.com/microsoft/vscode/blob/18136ed6ec4bfabc58664c8b656839709ea997e8/extensions/typescript-language-features/src/languageFeatures/util/textRendering.ts
https://github.com/microsoft/vscode/blob/18136ed6ec4bfabc58664c8b656839709ea997e8/extensions/typescript-language-features/src/test/unit/textRendering.test.ts
The code is copied from the VSCode extension. The difference is that the code runs in the server in the Angular extension, and runs in the client in the VSCode extension
Fixes https://github.com/angular/vscode-ng-language-service/issues/1902
cc @dylhunn
=> fix: support to show the tag info in the jsDoc

server/src/completion.ts, server/src/session.ts
Two changes are necessary to support autocompletion of block keywords:
1. The `@` keyword causes immediate completion
2. The new block completion item kind maps onto the keyword icon
=> feat: support block completions

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, client/src/client.ts, integration/lsp/ivy_spec.ts, package.json, pnpm-lock.yaml, server/package.json, server/src/session.ts, yarn.lock
This commit adds integration with the @angular/language-service package to get Angular-specific folding ranges in templates. At the moment, this only includes control flow blocks.
=> feat(server): Add folding range support for Angular template syntax

syntaxes/src/template-blocks.ts, syntaxes/template-blocks.json, syntaxes/test/data/template-blocks.html, syntaxes/test/data/template-blocks.html.snap
The block expression (.*) is currently inside a begin capture. TextMate captures are not able to be multiline. This commit updates the capturing groups so that the expression start capture is `(` and the end capture is `)`. This allows the start and end captures to appear on separate lines.
fixes #1945
=> fix(syntaxes): Support multiline block expressions

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, package.json, syntaxes/src/template-blocks.ts, syntaxes/template-blocks.json, syntaxes/test/cases.ts, syntaxes/test/data/template-blocks.html, syntaxes/test/data/template-blocks.html.snap
JS syntax has certain expectations for statements that do not hold true inside Angular template expressions. A missing trailing `;` in a variable assignment in a `for` expression will cause the javascript to never terminate. This commit updates the expression to use `expression.ng` instead.
fixes #1957
=> fix(syntaxes): Use expression.ng instead of JS for block expressions

syntaxes/expression.json, syntaxes/src/expression.ts, syntaxes/test/data/expression.html, syntaxes/test/data/expression.html.snap
While uncommon, single quotes can be used for HTML attribute values.
fixes #1912
=> fix(syntaxes): Single quote should end `as` alias match

client/src/client.ts, server/src/banner.ts, server/src/cmdline_utils.ts, server/src/server.ts, server/src/tests/version_provider_spec.ts, server/src/version_provider.ts
When the `typescript.tsdk` is empty, it should be ignored. Instead, the
logic previously would _always_ add an empty string tsdk to the
beginning of the probe locations. This would result in resolving the ts
server from the user's node modules rather than prefering the bundled
version as intended unless a different tsdk is specifically set in the
config.
Additionally, if the workspace has many roots, the first one would be
seen as a tsdk. While this would probably still result in the correct
behavior, the code is much easier to follow when the tsdk is a separate
option passed to the server.
(first 3 commits are from #1968)
=> fix(client,server): Correctly use bundled version unless tsdk is specified

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, CHANGELOG.md, package.json, pnpm-lock.yaml, server/package.json, yarn.lock
An early release of the v17.1.0 language service, so that early testers of 17.1.0 RC have working IDE support.
=> release: v17.1.0

client/src/client.ts, server/src/cmdline_utils.ts, server/src/server.ts, server/src/session.ts
Adds some logic to pass the oldest version of Angular that was detected in the workspace to the compiler so that it can produce the most compatible code possible.
Companion change to https://github.com/angular/angular/pull/54423.
=> fix: pass oldest Angular version in the workspace to the compiler

syntaxes/src/template-blocks.ts, syntaxes/template-blocks.json, syntaxes/test/data/template-blocks.html, syntaxes/test/data/template-blocks.html.snap
This updates the syntaxes to only match known block names instead of requiring a `{` at the end of the line when the block syntax is used.
fixes https://github.com/angular/angular/issues/53483
=> fix(syntaxes): Only match known block names

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, package.json, pnpm-lock.yaml, syntaxes/BUILD.bazel, syntaxes/let-declaration.json, syntaxes/src/build.ts, syntaxes/src/template-let-declaration.ts, syntaxes/test/cases.ts, syntaxes/test/data/let-declaration.html, syntaxes/test/data/let-declaration.html.snap
Adds highlighting support for the new `@let` syntax.
Example inside vscode:
=> feat(syntaxes): add support for let declarations

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, client/src/client.ts, package.json, pnpm-lock.yaml, server/src/cmdline_utils.ts, server/src/server.ts, server/src/session.ts, yarn.lock
Disables the `@let` syntax for projects that run an Angular version less than 18.1.
=> fix(server): disable let syntax when not supported

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, package.json, syntaxes/inline-template.json, syntaxes/src/inline-template.ts
Cleans up some syntax configurations. See individual commits.
=> Syntax cleanup

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, package.json, pnpm-lock.yaml, syntaxes/src/inline-styles.ts, syntaxes/src/inline-template.ts, syntaxes/src/template-tag.ts, tsconfig.json, yarn.lock
This fixes the compilation issue where node & ts.dom had conflicting types for `AbortSignal`
=> chore: update node types.

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, package.json, syntaxes/inline-template.json, syntaxes/src/inline-template.ts, syntaxes/test/data/inline-template.ts.snap
note: template.tag.ng isn't used here and needs to be directly injected into source.ts scopes at the top level because it relies entirely on the injectionSelector to filter its matching out of non-html tag contexts. Since we don't have any scopes that match HTML tags, we rely entirely on the text.html.derivative pattern matching and apply the tag scope via injectionSelector only rather than being able to include it in a pattern list of another match.
fixes #2053
=> fix(syntaxes): inject template tags to top-level source.ts (#2058)

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, package.json, pnpm-lock.yaml, syntaxes/src/inline-styles.ts, syntaxes/src/inline-template.ts, syntaxes/src/template-tag.ts, tsconfig.json, yarn.lock
This fixes the compilation issue where node & ts.dom had conflicting types for `AbortSignal`
=> chore: update node types. (#2055)

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, package.json, syntaxes/inline-template.json, syntaxes/src/inline-template.ts
We rely on the `injectionSelector` to prevent matching our grammars in contexts which they should not apply. The `injectionSelector` only applies when the grammar is injected to the file via `injectTo`. Otherwise, the grammer is applied directly when it is included in the `patterns` array of another match.
fixes #2062
=> fix(syntaxes): add back block syntaxes to injection for entire TS file

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, package.json, pnpm-lock.yaml, syntaxes/src/template-blocks.ts, syntaxes/template-blocks.json, syntaxes/test/data/template-blocks.html.snap
This commit updates the embedded languages of template.blocks.ng to more accurately reflect content. It also makes expressions switch the javascript language. Lastly, this updates the block capture to name the entire content control.block.ng rather than just contentName, which excluded the block name and expression.
=> refactor(syntaxes): Update embedded languages and block name

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, .vscode/tasks.json, client/src/client.ts, package.json, pnpm-lock.yaml, server/src/session.ts, yarn.lock
This integrates Angular's code refactorings into the extension, so that those are communicated via the LSP to VSCode.
=> feat: integrate code refactorings from language-service via LSP

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, client/src/client.ts, package.json, pnpm-lock.yaml, server/package.json, server/src/cmdline_utils.ts, server/src/server.ts, server/src/session.ts, yarn.lock
Allow the language service plugin to pass diagnostic codes that should be ignored via the PluginConfig.
This change corresponds to PR angular/angular#57675.
In addition to providing an easily patchable array and a command-line option, it's also wired up to the extension settings:
Fixes #1243
=> feat(language-service): Allow specific diagnostics to be suppressed

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, package.json, pnpm-lock.yaml, server/src/session.ts, yarn.lock
Refactorings can create warnings too. This commit integrates this into the language service extension.
=> refactor: prepare for v19 refactorings

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, CHANGELOG.md, package.json, pnpm-lock.yaml, yarn.lock
Cuts a new pre-release for the v19 VSCode extension.
=> release: cut pre-release `v19.0.0-next.1` for vscode extension

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, .bazelignore, .circleci/config.yml, WORKSPACE, integration/lsp/BUILD.bazel, integration/lsp/ivy_spec.ts, integration/lsp/test_utils.ts, integration/pre_standalone_project/BUILD.bazel, integration/pre_standalone_project/app/app.component.ts, integration/pre_standalone_project/app/app.module.ts, integration/pre_standalone_project/app/foo.component.html, integration/pre_standalone_project/app/foo.component.ts, integration/pre_standalone_project/package.json, integration/pre_standalone_project/pnpm-lock.yaml, integration/pre_standalone_project/pnpm-workspace.yaml, integration/pre_standalone_project/tsconfig.json, integration/test_constants.ts, package.json, pnpm-lock.yaml, yarn.lock
=> Prepare for v19 rc.0 release

client/src/client.ts
Angular may not be installed at the project root. We should look for `package.json` roots and determine the `@angular/core` version based on these folders.
Related to: https://github.com/angular/angular/issues/58546
=> fix: improve detection of Angular core version in monorepo setup

CHANGELOG.md, package.json
Cuts a v19.0.1 vscode extension release with a fix for the Angular core version detection.
=> build: cut 19.0.1 vscode extension release

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, package.json, pnpm-lock.yaml
This commit moves the Angular commands to a submenu. This was the intent initially but not enough time was spent to figure out how to do it correctly.
fixes #2076
=> fix(extension): Fix grouping of Angular commands into submenu

server/src/completion.ts, server/src/session.ts
The Angular Language Service does not return `InsertReplaceEdit`. There is no need to allow the developer to choose how to insert the completion.
```
For example, `<button (c|) />`.
^^__________Insert edit
^^ ^________Replace edit
```
If the LS returns the `InsertReplaceEdit` as shown above, selecting "Insert" by the developer results in `(click)="")`, and selecting "Replace" results in `(click)=""`.
Now in the vscode, the default `editor.suggest.insertMode` value for HTML is `Replace`, for ts is `Insert`, So this leads to a bug in the ts file.
Fixes https://github.com/angular/vscode-ng-language-service/issues/2137
=> fix: replace the closing symbol for inputs/outputs.

README.md
Updates the link in README for `nvim-lspconfig` configuration.
=> docs: update nvim-lspconfig link

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, CHANGELOG.md, package.json, pnpm-lock.yaml, yarn.lock
Updates the language-service version to fix issues like: https://github.com/angular/vscode-ng-language-service/issues/2153
Bumps the version of the repository so that we can cut a new VSCode extension release.
I've verified locally that this fixes the issues as expected. We just didn't have a extension release with the latest version.
=> build: update language-service version and bump version for release

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=, client/src/client.ts, client/src/embedded_support.ts, integration/project/tsconfig.json, integration/workspace/tsconfig.json, package.json, pnpm-lock.yaml, syntaxes/BUILD.bazel, syntaxes/host-object-literal.json, syntaxes/src/build.ts, syntaxes/src/host-object-literal.ts, syntaxes/test/cases.ts, syntaxes/test/data/host-object-literal.ts, syntaxes/test/data/host-object-literal.ts.snap
Makes the necessary changes on the vscode extension side to enable https://github.com/angular/angular/pull/60267, including:
* Looking for completions, quick info etc inside the `host` property.
* Syntax highlighting for the `host` object literal.
=> feat: add support for host bindings

syntaxes/expression.json, syntaxes/src/expression.ts, syntaxes/test/data/expression.html.snap, syntaxes/test/data/template-blocks.html.snap, syntaxes/test/data/template-tag.html.snap
This PR adds the `punctuationSemicolon` pattern to the `expression` grammar's pattern list, which ensures that the `punctuation.terminator` scope is actually applied to the matching syntax.
=> fix(syntaxes): Semicolons not tokenized

syntaxes/src/template-blocks.ts, syntaxes/template-blocks.json, syntaxes/test/data/template-blocks.html, syntaxes/test/data/template-blocks.html.snap
This PR updates the TM grammar for flow-control block expressions to tokenize `track` as a keyword.
- Separate the valid sub-expressions of a `@for`/`@if` header into their own "clause" patterns (helps to avoid highlighting `track` as a keyword in the wrong context)
- Assign `keyword.control.track.ng` scope to the `track` token at the beginning of a "track-by" clause
- The `item` binding in `item of items` is now `constant` instead of `readwrite`, following the same logic mentioned in #2160. Again, happy to revert this change if that's unwanted.
=> fix(syntaxes): `keyword` token for `track`

syntaxes/let-declaration.json, syntaxes/src/template-let-declaration.ts, syntaxes/test/data/let-declaration.html.snap
This PR tweaks the TM scopes applied to `@let` declarations to tokenize the bound identifier as a variable. This brings the grammar into closer alignment with, e.g., TypeScript's TM grammar.
- The bound identifier gets its own scope, `variable.other.constant.ng`.
- `meta.definition.variable.ng` scope now covers the entire declaration instead of just the identifier and the initializer expression.
I went with `variable.other.constant.ng` instead of `variable.other.readwrite.ng` because it's technically correct (you cannot reassign a `@let` binding), but it does make it inconsistent with the rest of the grammar, which uses `readwrite` everywhere. I'd be happy to change it if there's a preference for consistency over correctness. My daily driver theme (and likely most themes on the …
=> fix(syntaxes): `variable` token for `@let` binding
